/**
 * Cheap guard — runs in the package's normal `npm test`.
 *
 * The Health scale corpus is a FIXTURE: every He-stage after this one is judged
 * by re-running the phases and diffing the numbers, and that comparison is only
 * meaningful if the corpus is byte-identical between runs. This file pins the
 * shape (per-table counts, key fields, id schemes) and the identity
 * (`corpusFingerprint`). A factory tweak that changes a single generated byte
 * fails here FIRST, before it silently invalidates a published baseline.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  HEALTH_LEDGER_TABLE_KEYS,
  HEALTH_LEDGER_TABLE_NAMES,
  HEALTH_WAVE_A_TABLE_COUNT,
} from '../../../../src/features/health/local/schema';

import { enableDevAssertions } from './lib/dev-global';
import {
  HEALTH_DEFAULT_SEED,
  HEALTH_DEVICE_COUNT,
  HEALTH_REFERENCE_SPEC,
  corpusFingerprint,
  daysFor,
  generateHealthLedger,
  lwwStampCount,
  rowCounts,
  scaleId,
  totalRows,
} from './lib/health-ledger-factory';

enableDevAssertions();

const SPEC = { years: 1, adults: 1, seed: HEALTH_DEFAULT_SEED };

describe('health corpus — registry agreement', () => {
  it('covers exactly the 8 Wave A tables and nothing else', () => {
    const ledger = generateHealthLedger(SPEC);
    expect(HEALTH_LEDGER_TABLE_NAMES).toHaveLength(HEALTH_WAVE_A_TABLE_COUNT);
    for (const table of HEALTH_LEDGER_TABLE_NAMES) {
      expect(Array.isArray(ledger[table])).toBe(true);
      expect(ledger[table].length).toBeGreaterThan(0);
    }
  });

  it('keys every row on the field the registry declares', () => {
    const ledger = generateHealthLedger(SPEC);
    for (const table of HEALTH_LEDGER_TABLE_NAMES) {
      const keyField = HEALTH_LEDGER_TABLE_KEYS[table];
      const keys = new Set<string>();
      for (const row of ledger[table]) {
        const key = row[keyField];
        expect(typeof key).toBe('string');
        keys.add(String(key));
      }
      // Duplicate row keys would make the LWW map lossy and every count wrong.
      expect(keys.size).toBe(ledger[table].length);
    }
  });

  it('is a household that has SYNCED — the watermark map is populated', () => {
    const ledger = generateHealthLedger(SPEC);
    const stamps = lwwStampCount(ledger);
    expect(stamps).toBeGreaterThan(totalRows(ledger));
    // One stamp per FIELD per row, so the ratio is the mean column count.
    expect(stamps / totalRows(ledger)).toBeGreaterThan(5);
  });
});

describe('health corpus — determinism', () => {
  it('generates byte-identical ledgers from the same spec', () => {
    const a = JSON.stringify(generateHealthLedger(SPEC));
    const b = JSON.stringify(generateHealthLedger(SPEC));
    expect(a).toBe(b);
  });

  it('has no Math.random() and no Date.now() anywhere in the generator', () => {
    // The whole contract of a fixture is "the same bytes forever". A single
    // `Math.random()` would make every published number unreproducible, and it
    // is the kind of thing that gets added in a hurry and noticed in a month.
    const files = ['health-ledger-factory.ts', 'health-oplog-factory.ts', 'health-home-loaders.ts'];
    for (const file of files) {
      const source = readFileSync(
        fileURLToPath(new URL(`./lib/${file}`, import.meta.url)),
        'utf8',
      );
      // Strip block and line comments: the prose explains WHY these are banned.
      const code = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
      expect(code, `${file} must not call Math.random()`).not.toMatch(/Math\.random\s*\(/);
      expect(code, `${file} must not call Date.now()`).not.toMatch(/Date\.now\s*\(/);
    }
  });

  it('pins the corpus fingerprint', () => {
    expect(corpusFingerprint(HEALTH_REFERENCE_SPEC)).toMatchSnapshot();
  });
});

describe('health corpus — composition', () => {
  it('pins per-table row counts at 1y / 5y / 10y', () => {
    expect({
      '1y': rowCounts({ years: 1, seed: HEALTH_DEFAULT_SEED }),
      '5y': rowCounts({ years: 5, seed: HEALTH_DEFAULT_SEED }),
      '10y': rowCounts({ years: 10, seed: HEALTH_DEFAULT_SEED }),
    }).toMatchSnapshot();
  });

  it('pins the scale ids the recorder stamps on every record', () => {
    expect([1, 3, 5, 10].map((years) => scaleId({ years, seed: HEALTH_DEFAULT_SEED }))).toMatchSnapshot();
  });

  it('agrees with the generated ledger it describes', () => {
    for (const years of [1, 5]) {
      const spec = { years, seed: HEALTH_DEFAULT_SEED };
      const counts = rowCounts(spec);
      const ledger = generateHealthLedger(spec);
      for (const table of HEALTH_LEDGER_TABLE_NAMES) {
        expect(ledger[table].length, `${table} @ ${years}y`).toBe(counts[table]);
      }
      expect(totalRows(ledger)).toBe(scaleId(spec).rows);
    }
  });

  it('counts days with 365.25, so a leap day is not silently dropped', () => {
    expect(daysFor(1)).toBe(365);
    expect(daysFor(4)).toBe(1461);
    expect(daysFor(10)).toBe(3653);
  });

  it('is ONE user on TWO devices, not two users', () => {
    const ledger = generateHealthLedger(SPEC);
    const userIds = new Set(ledger.weightEntries.map((row) => String(row.user_id)));
    expect(userIds.size).toBe(1);
    expect(HEALTH_DEVICE_COUNT).toBe(2);
    // `adults` is pinned by the factory: a Health household cannot have two.
    expect(scaleId({ years: 1, adults: 4, seed: HEALTH_DEFAULT_SEED }).adults).toBe(1);
  });
});
