/**
 * `HealthHabitDetailScreen` — the donor's `HabitDetailView`, driven directly.
 *
 * `habits.screen.test.tsx` mocks this whole screen into a five-button stub so
 * it can test `HealthHabitsScreen`'s WIRING (which callback reaches which
 * store call) without also re-deriving this screen's own arithmetic.
 * `screens/__tests__/HealthSectionScreens.test.tsx` renders the real thing
 * for exactly one path — the delete confirmation. Neither exercises the
 * statistics tiles, the completion-rate caption's two forms, the 28-day
 * history grid's three cell states, the archived banner, editing (which
 * embeds the real `HealthHabitForm`), or the notes card — this file owns
 * those, against the real component with plain callback spies standing in
 * for the screen that would normally own the store calls.
 *
 * `AppBarChart` (inside the shared `HealthHabitStats`) is mocked to its data
 * contract — it is a chart primitive with its own coverage, owned elsewhere.
 */

/* eslint-disable @typescript-eslint/no-require-imports -- jest.mock factories are hoisted above imports, so they must use require() */
import React from 'react';
import { StyleSheet } from 'react-native';
import ReactTestRenderer, { act } from 'react-test-renderer';

import { Icon } from '@components/ui/Icon';
import { ThemeProvider } from '@contexts/ThemeContext';

import { categoryIcon, habitHistory, type Habit } from '../../healthHabitsStorage';
import {
  HealthHabitDetailScreen,
  type HealthHabitDetailScreenProps,
} from '../../screens/HealthHabitDetailScreen';

type Rendered = ReactTestRenderer.ReactTestRenderer;

const TODAY = '2026-07-13'; // Monday
const FIXED_NOW = new Date(2026, 6, 13, 12, 0, 0);

jest.mock('react-native/Libraries/Utilities/useWindowDimensions', () => ({
  __esModule: true,
  default: () => ({ width: 393, height: 852, scale: 3, fontScale: 1 }),
}));

jest.mock('@components/ui/AppBarChart', () => {
  const ReactMock = require('react');
  const { View } = require('react-native');
  return {
    AppBarChart: () => ReactMock.createElement(View, { testID: 'app-bar-chart' }),
  };
});

function habit(over: Partial<Habit> = {}): Habit {
  return {
    id: 'sleep',
    name: 'Sleep 7+ hours',
    icon: 'sleep-habit',
    category: 'wellness',
    templateId: null,
    timeOfDay: 'evening',
    frequency: 'daily',
    customDays: null,
    reminderTime: null,
    reminderEnabled: false,
    targetDuration: null,
    notes: null,
    archived: false,
    sortOrder: 0,
    days: [],
    createdAt: '2026-06-01T00:00:00.000Z',
    ...over,
  };
}

/**
 * Concatenated text of a subtree, with the icon primitive's own subtree skipped.
 *
 * `<Icon>` resolves a name against the active brand's PNG kit
 * (`src/brand/icons.generated.ts` — GENERATED, regenerated by `icons:build` for
 * whichever APP_BRAND is being built) and falls through to `<Ionicons>` when
 * that kit has no such slug. The PNG branch contributes no text; the Ionicons
 * branch renders a `<Text>` holding a glyph codepoint — or a literal "?" when
 * the name is not an Ionicons slug either. Health's `history`, `streak`,
 * `sleep-habit`, … exist in `brands/symply-health` but not in the
 * `brands/symply-house` kit Jest pins, so the icon beside a button label leaked
 * into that label ("?Unarchive"). Labels are what these assertions are about,
 * so glyphs are excluded rather than absorbed.
 */
function allText(node: unknown): string {
  if (node == null) return '';
  if (typeof node === 'string') return node;
  if (typeof node === 'number') return String(node);
  if (Array.isArray(node)) return node.map(allText).join('');
  if ((node as { type?: unknown }).type === Icon) return '';
  return allText((node as { children?: unknown }).children);
}

function byTestId(tree: Rendered, id: string) {
  return tree.root.findAll((n) => typeof n.type === 'string' && n.props?.testID === id);
}

function textOf(tree: Rendered, id: string): string {
  const node = byTestId(tree, id)[0];
  if (!node) return '';
  // An <Icon> that falls back to Ionicons renders as TEXT — an icon-font
  // codepoint in the Private Use Area — so a button with a leading glyph reads
  // as " Unarchive" and never equals its label. Drop PUA characters (and
  // the "?" a missing glyph renders as) so this returns the words on screen.
  return allText(node)
    .replace(/[-]/g, '')
    .replace(/^\?+/, '')
    .trim();
}

/** `HealthStatTiles` puts label AND value under one testID; read the a11y label instead. */
function statLabelOf(tree: Rendered, id: string): string {
  return byTestId(tree, id)[0]?.props.accessibilityLabel ?? '';
}

/** The composite carrying `testID` (the Pressable, not its host View). */
function pressable(tree: Rendered, testID: string) {
  return tree.root.find((n) => n.props?.testID === testID && typeof n.props?.onPress === 'function');
}

function press(tree: Rendered, testID: string) {
  act(() => pressable(tree, testID).props.onPress());
}

function input(tree: Rendered, testID: string) {
  return tree.root.find(
    (n) => (n.type as unknown as string) === 'TextInput' && n.props?.testID === testID,
  );
}

function type(tree: Rendered, testID: string, text: string) {
  act(() => input(tree, testID).props.onChangeText(text));
}

interface Callbacks {
  onClose: jest.Mock;
  onToggle: jest.Mock;
  onSave: jest.Mock;
  onArchive: jest.Mock;
  onDelete: jest.Mock;
}

async function render(theHabit: Habit, overrides: Partial<HealthHabitDetailScreenProps> = {}) {
  const callbacks: Callbacks = {
    onClose: jest.fn(),
    onToggle: jest.fn(),
    onSave: jest.fn(),
    onArchive: jest.fn(),
    onDelete: jest.fn(),
  };
  let tree!: Rendered;
  await act(async () => {
    tree = ReactTestRenderer.create(
      <ThemeProvider>
        <HealthHabitDetailScreen habit={theHabit} {...callbacks} {...overrides} />
      </ThemeProvider>,
    );
  });
  return { tree, ...callbacks };
}

beforeEach(() => {
  jest.useFakeTimers().setSystemTime(FIXED_NOW);
});

afterEach(() => {
  jest.useRealTimers();
});

/* ------------------------------------------------------------------ */
/* Header — identity, schedule, reminder, archived banner               */
/* ------------------------------------------------------------------ */

describe('HealthHabitDetailScreen — header', () => {
  it('HEALTH-HABIT-400: shows category · time-of-day, the schedule in words, and the reminder line', async () => {
    const { tree } = await render(
      habit({
        category: 'fitness',
        timeOfDay: 'morning',
        frequency: 'weekdays',
        reminderEnabled: true,
        reminderTime: '07:00',
      }),
    );

    expect(allText(tree.toJSON())).toContain('Fitness · Morning');
    expect(textOf(tree, 'health-habit-detail-schedule')).toBe('Monday to Friday');
    expect(allText(tree.toJSON())).toContain('Reminder at 07:00');
  });

  it('HEALTH-HABIT-401: no reminder set (or disabled) reads "No reminder"', async () => {
    const { tree: off } = await render(habit({ reminderEnabled: false, reminderTime: '07:00' }));
    expect(allText(off.toJSON())).toContain('No reminder');

    const { tree: noTime } = await render(habit({ reminderEnabled: true, reminderTime: null }));
    expect(allText(noTime.toJSON())).toContain('No reminder');
  });

  it('HEALTH-HABIT-402: an archived habit shows the banner; an active one does not', async () => {
    const { tree: archived } = await render(habit({ archived: true }));
    expect(byTestId(archived, 'health-habit-detail-archived')).toHaveLength(1);

    const { tree: active } = await render(habit({ archived: false }));
    expect(byTestId(active, 'health-habit-detail-archived')).toHaveLength(0);
  });

  it('HEALTH-HABIT-403: Close fires onClose', async () => {
    const { tree, onClose } = await render(habit());
    press(tree, 'health-habit-detail-close');
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it('HEALTH-HABIT-403b: a habit with no icon of its own falls back to its CATEGORY icon', async () => {
    // A custom habit created before an icon was chosen (or one whose column
    // came back blank from the server) must still draw something on-brand
    // rather than an empty tile — the category's own icon.
    const { tree } = await render(habit({ icon: '', category: 'fitness' }));

    // Size 28 is unique to the header identity icon in this render (the close
    // button is 20, every action/stat icon smaller still).
    const identityIcon = tree.root.findAllByType(Icon).find((n) => n.props.size === 28);
    expect(identityIcon?.props.name).toBe(categoryIcon('fitness'));
  });
});

/* ------------------------------------------------------------------ */
/* Statistics                                                           */
/* ------------------------------------------------------------------ */

describe('HealthHabitDetailScreen — statistics', () => {
  it('HEALTH-HABIT-404: current / best / total read real streak arithmetic, dashed at zero', async () => {
    const { tree } = await render(habit({ days: [] }));

    expect(statLabelOf(tree, 'health-habit-detail-current')).toBe('Current: —');
    expect(statLabelOf(tree, 'health-habit-detail-best')).toBe('Best: —');
    expect(statLabelOf(tree, 'health-habit-detail-total')).toBe('Total: 0');
  });

  it('HEALTH-HABIT-405: a live streak and a longer past streak are both reported', async () => {
    const { tree } = await render(
      habit({
        // Live streak: today + yesterday (2). Past streak: three days further
        // back, broken by a gap — the LONGEST-ever streak, not the live one.
        days: [
          '2026-07-13',
          '2026-07-12',
          '2026-07-08',
          '2026-07-07',
          '2026-07-06',
        ],
      }),
    );

    expect(statLabelOf(tree, 'health-habit-detail-current')).toBe('Current: 2 d');
    expect(statLabelOf(tree, 'health-habit-detail-best')).toBe('Best: 3 d');
    expect(statLabelOf(tree, 'health-habit-detail-total')).toBe('Total: 5');
  });

  it('HEALTH-HABIT-406: the rate caption is silent about a window with nothing due yet', async () => {
    // Created TODAY, so the 30-day window has zero expected days behind it.
    const { tree } = await render(
      habit({ frequency: 'weekends', createdAt: '2026-07-13T00:00:00.000Z' }),
    );

    expect(textOf(tree, 'health-habit-detail-rate')).toBe('Not scheduled yet in this window.');
  });

  it('HEALTH-HABIT-407: the rate caption states percent, count and singular/plural "day(s)"', async () => {
    // Created well before the 30-day window: every one of the 30 days is
    // expected (daily), and only TODAY was ticked — 1/30 ≈ 3%. Plural "days".
    const { tree: daily } = await render(
      habit({ frequency: 'daily', days: [TODAY], createdAt: '2026-06-01T00:00:00.000Z' }),
    );
    expect(textOf(daily, 'health-habit-detail-rate')).toBe(
      '3% of the 30 scheduled days in the last 30 — days this habit is not due are not counted against it.',
    );

    // Created 29 days into the 30-day window: exactly ONE day is expected
    // (today, the only day both scheduled-for and existing) — the SINGULAR
    // "day" form, at 100% since it was ticked.
    const { tree: oneDay } = await render(
      habit({ frequency: 'daily', days: [TODAY], createdAt: TODAY }),
    );
    expect(textOf(oneDay, 'health-habit-detail-rate')).toBe(
      '100% of the 1 scheduled day in the last 30 — days this habit is not due are not counted against it.',
    );
  });
});

/* ------------------------------------------------------------------ */
/* History grid                                                         */
/* ------------------------------------------------------------------ */

describe('HealthHabitDetailScreen — 28-day history', () => {
  it('HEALTH-HABIT-408: the accessibility summary counts only DONE days out of 28', async () => {
    const { tree } = await render(habit({ frequency: 'daily', days: [TODAY, '2026-07-12'] }));

    expect(byTestId(tree, 'health-habit-detail-history')[0].props.accessibilityLabel).toBe(
      '2 of the last 28 days completed',
    );
  });

  it('HEALTH-HABIT-409: a weekends-only habit reads mid-week days as "not scheduled" — a THIRD, transparent state, not "missed"', async () => {
    // TODAY (2026-07-13) is a Monday — not scheduled for a weekends-only habit,
    // and never ticked, so most of the 28-day strip must render as the
    // literal `transparent` fill (unscheduled), never the grey "missed" one a
    // plain done/not-done grid would show for every untouched day.
    const theHabit = habit({ frequency: 'weekends', days: [] });
    const { tree } = await render(theHabit);

    const expectedUnscheduled = habitHistory(theHabit, 28, TODAY).filter(
      (d) => !d.scheduled,
    ).length;
    expect(expectedUnscheduled).toBeGreaterThan(0); // sanity: the fixture is meaningful

    // Cells carry no per-day testID (the grid is a plain 28-`View` strip), so
    // they are found by their own fixed geometry (`styles.historyCell`),
    // scoped to host `View`s only.
    const cells = tree.root.findAll(
      (n) =>
        typeof n.type === 'string' &&
        String(n.type) === 'View' &&
        StyleSheet.flatten(n.props?.style)?.width === 22 &&
        StyleSheet.flatten(n.props?.style)?.height === 22,
    );
    const transparentCount = cells.filter(
      (c) => StyleSheet.flatten(c.props.style).backgroundColor === 'transparent',
    ).length;

    expect(cells).toHaveLength(28);
    expect(transparentCount).toBe(expectedUnscheduled);

    expect(allText(tree.toJSON())).toContain(
      'Filled = done · grey = scheduled and missed · outline = not scheduled',
    );
  });
});

/* ------------------------------------------------------------------ */
/* Actions                                                              */
/* ------------------------------------------------------------------ */

describe('HealthHabitDetailScreen — actions', () => {
  it('HEALTH-HABIT-410: the primary button reflects today and toggles it', async () => {
    const { tree: notDone, onToggle } = await render(habit({ days: [] }));
    expect(textOf(notDone, 'health-habit-detail-toggle')).toContain('Mark as complete');

    press(notDone, 'health-habit-detail-toggle');
    expect(onToggle).toHaveBeenCalledWith(expect.objectContaining({ id: 'sleep' }), TODAY);

    const { tree: done } = await render(habit({ days: [TODAY] }));
    expect(textOf(done, 'health-habit-detail-toggle')).toContain('Completed today');
    expect(
      byTestId(done, 'health-habit-detail-toggle')[0].props.accessibilityLabel,
    ).toBe('Mark as not done today');
  });

  it('HEALTH-HABIT-411: Archive / Unarchive labels flip with state and call onArchive with the OPPOSITE flag', async () => {
    const { tree: active, onArchive: archiveIt } = await render(habit({ archived: false }));
    expect(textOf(active, 'health-habit-detail-archive')).toBe('Archive');
    press(active, 'health-habit-detail-archive');
    expect(archiveIt).toHaveBeenCalledWith(expect.objectContaining({ id: 'sleep' }), true);

    const { tree: archived, onArchive: unarchiveIt } = await render(habit({ archived: true }));
    expect(textOf(archived, 'health-habit-detail-archive')).toBe('Unarchive');
    press(archived, 'health-habit-detail-archive');
    expect(unarchiveIt).toHaveBeenCalledWith(expect.objectContaining({ id: 'sleep' }), false);
  });

  it('HEALTH-HABIT-412: Edit opens the real form seeded from the habit, and toggles its own label', async () => {
    const { tree } = await render(
      habit({ name: 'Stretch', notes: 'after the school run', frequency: 'weekdays' }),
    );

    expect(byTestId(tree, 'health-habit-edit-form')).toHaveLength(0);
    expect(textOf(tree, 'health-habit-detail-edit')).toBe('Edit');

    press(tree, 'health-habit-detail-edit');

    expect(byTestId(tree, 'health-habit-edit-form')).toHaveLength(1);
    expect(input(tree, 'health-habit-edit-name').props.value).toBe('Stretch');
    expect(textOf(tree, 'health-habit-detail-edit')).toBe('Close');
    // Editing hides the notes card — the form's own NOTES field is the one
    // editable copy on screen; a second, stale one would be confusing.
    expect(byTestId(tree, 'health-habit-detail-notes')).toHaveLength(0);

    // Pressing it again (without submitting) closes it, discarding nothing
    // because nothing was sent.
    press(tree, 'health-habit-detail-edit');
    expect(byTestId(tree, 'health-habit-edit-form')).toHaveLength(0);
  });

  it('HEALTH-HABIT-413: submitting the edit form calls onSave with the habit and the draft, and closes the editor', async () => {
    const { tree, onSave } = await render(habit({ name: 'Stretch' }));
    press(tree, 'health-habit-detail-edit');

    type(tree, 'health-habit-edit-name', 'Evening stretch');
    press(tree, 'health-habit-edit-submit');

    expect(onSave).toHaveBeenCalledWith(
      expect.objectContaining({ id: 'sleep' }),
      expect.objectContaining({ name: 'Evening stretch' }),
    );
    expect(byTestId(tree, 'health-habit-edit-form')).toHaveLength(0);
  });

  it('HEALTH-HABIT-414: Cancel on the edit form closes it without calling onSave', async () => {
    const { tree, onSave } = await render(habit());
    press(tree, 'health-habit-detail-edit');

    press(tree, 'health-habit-edit-cancel');

    expect(onSave).not.toHaveBeenCalled();
    expect(byTestId(tree, 'health-habit-edit-form')).toHaveLength(0);
  });
});

/* ------------------------------------------------------------------ */
/* Notes card                                                           */
/* ------------------------------------------------------------------ */

describe('HealthHabitDetailScreen — notes', () => {
  it('HEALTH-HABIT-415: notes render when present and not editing; nothing renders when blank', async () => {
    const { tree: withNotes } = await render(habit({ notes: 'Stretch before, not after' }));
    expect(textOf(withNotes, 'health-habit-detail-notes')).toBe('Stretch before, not after');

    const { tree: noNotes } = await render(habit({ notes: null }));
    expect(byTestId(noNotes, 'health-habit-detail-notes')).toHaveLength(0);
  });
});
