#!/bin/bash
echo "=========================================="
echo "Checking for Failed Reports"
echo "=========================================="
echo ""
echo "Option 1: Check Cloudflare Dashboard"
echo "  https://dash.cloudflare.com"
echo "  → Workers & Pages → simple-house-api → Logs"
echo ""
echo "Option 2: Use wrangler tail (requires Node 20+)"
echo "  cd backend && wrangler tail --env production"
echo ""
echo "Option 3: Query database for failed reports"
echo "  wrangler d1 execute simple-house-db --remote --command \\"
echo "    \"SELECT id, filename, status, error_message, updated_at FROM reports WHERE status = 'failed' ORDER BY updated_at DESC LIMIT 5;\""
echo ""
echo "Option 4: Check Lambda logs"
echo "  aws logs tail /aws/lambda/inspection-report-processor --since 10m --region us-east-1"
echo ""
