-- Migration: Savings & Registered accounts
-- Created: 2026-07-03

CREATE TABLE IF NOT EXISTS savings_categories (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    icon TEXT,
    color TEXT,
    is_essential INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(household_id, name)   -- W3: makes default-category seeding idempotent under concurrent first-open
);
CREATE INDEX IF NOT EXISTS savings_categories_household_idx ON savings_categories(household_id);

CREATE TABLE IF NOT EXISTS savings_income_entries (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    member_id TEXT REFERENCES household_members(id) ON DELETE SET NULL,
    source_type TEXT NOT NULL,
    label TEXT NOT NULL,
    amount_cents INTEGER NOT NULL,
    income_date TEXT NOT NULL,
    currency TEXT NOT NULL DEFAULT 'CAD',
    notes TEXT,
    template_id TEXT,            -- logical FK → savings_income_templates(id); set when this row was generated by applying a recurring-income template (Phase 4)
    period TEXT,                 -- 'YYYY-MM' when generated by applying a template; NULL for ad-hoc income
    created_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS savings_income_household_idx ON savings_income_entries(household_id);
CREATE INDEX IF NOT EXISTS savings_income_date_idx ON savings_income_entries(household_id, income_date);
-- Idempotent apply-templates: at most one income row per (template, month) — mirrors the recurring-payments design (C1)
CREATE UNIQUE INDEX IF NOT EXISTS savings_income_template_period_idx
  ON savings_income_entries(template_id, period) WHERE template_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS savings_spending_entries (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    category_id TEXT REFERENCES savings_categories(id) ON DELETE SET NULL,
    label TEXT NOT NULL,
    amount_cents INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'CAD',
    spending_date TEXT NOT NULL,
    notes TEXT,
    recurring_payment_id TEXT,   -- logical FK → savings_recurring_payments(id); plain TEXT to avoid migration table-order coupling (relationship enforced in service)
    period TEXT,                 -- 'YYYY-MM' when this row was generated by applying a recurring payment; NULL for ad-hoc spend
    created_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS savings_spending_household_idx ON savings_spending_entries(household_id);
CREATE INDEX IF NOT EXISTS savings_spending_date_idx ON savings_spending_entries(household_id, spending_date);
-- Idempotent recurring-apply: at most one spend row per (recurring payment, month)
CREATE UNIQUE INDEX IF NOT EXISTS savings_spending_recurring_period_idx
  ON savings_spending_entries(recurring_payment_id, period) WHERE recurring_payment_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS savings_income_templates (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    member_id TEXT REFERENCES household_members(id) ON DELETE SET NULL,
    source_type TEXT NOT NULL,
    label TEXT NOT NULL,
    amount_cents INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'CAD',
    day_of_month INTEGER,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS savings_income_templates_household_idx ON savings_income_templates(household_id);

CREATE TABLE IF NOT EXISTS savings_goals (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    target_amount_cents INTEGER NOT NULL,
    current_amount_cents INTEGER NOT NULL DEFAULT 0,
    target_date TEXT,
    months_of_expenses INTEGER,
    monthly_allocation_cents INTEGER,
    currency TEXT NOT NULL DEFAULT 'CAD',
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS savings_goals_household_idx ON savings_goals(household_id);

CREATE TABLE IF NOT EXISTS registered_accounts (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    member_id TEXT REFERENCES household_members(id) ON DELETE SET NULL,
    account_type TEXT NOT NULL,
    institution TEXT,
    balance_cents INTEGER NOT NULL DEFAULT 0,
    starting_room_cents INTEGER,            -- user-entered CURRENT-year available room (RRSP: NOA deduction limit; TFSA: CRA My Account room)
    annual_limit_override_cents INTEGER,    -- optional: user-entered this-year limit; overrides the CRA constant when present (guards against a stale SAVINGS_LIMITS entry)
    regular_contribution_cents INTEGER,     -- optional: monthly "regular" contribution amount (e.g. RRSP employer matching) used by the apply-regular action
    room_as_of_date TEXT,
    prior_earned_income_cents INTEGER,
    pension_adjustment_cents INTEGER,
    currency TEXT NOT NULL DEFAULT 'CAD',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS registered_accounts_household_idx ON registered_accounts(household_id);

CREATE TABLE IF NOT EXISTS registered_transactions (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES registered_accounts(id) ON DELETE CASCADE,
    type TEXT NOT NULL,                      -- 'contribution' | 'withdrawal'
    kind TEXT NOT NULL DEFAULT 'manual',     -- 'regular' (e.g. RRSP employer matching, recurring) | 'manual' (ad-hoc this year)
    amount_cents INTEGER NOT NULL,
    transaction_date TEXT NOT NULL,
    tax_year INTEGER,
    period TEXT,                             -- 'YYYY-MM' when auto-generated by applying a regular contribution; NULL for ad-hoc
    notes TEXT,
    created_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS registered_transactions_account_idx ON registered_transactions(account_id);
-- Idempotent regular-contribution apply: at most one auto row per (account, month)
CREATE UNIQUE INDEX IF NOT EXISTS registered_tx_regular_period_idx
  ON registered_transactions(account_id, period) WHERE period IS NOT NULL;

-- === Phase 5 additions (Monthly Payments + AI import) — created here in the single additive 0067 migration ===

CREATE TABLE IF NOT EXISTS savings_recurring_payments (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    category_id TEXT REFERENCES savings_categories(id),
    label TEXT NOT NULL,
    amount_cents INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'CAD',
    day_of_month INTEGER,                    -- optional due day 1-31
    group_label TEXT,                        -- e.g. 'Mortgages' / 'Other' subtotal grouping from the source sheet
    is_essential INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    source TEXT NOT NULL DEFAULT 'manual',   -- 'manual' | 'ai_import'
    created_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS savings_recurring_payments_household_idx ON savings_recurring_payments(household_id);

CREATE TABLE IF NOT EXISTS savings_import_jobs (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending_upload',  -- pending_upload|uploaded|analyzing|ready|committed|failed
    source_kind TEXT NOT NULL,                       -- 'file' | 'image' | 'text' | 'drive'
    file_key TEXT,                                   -- R2 object key (NULL for pasted text)
    file_name TEXT,
    mime_type TEXT,
    size_bytes INTEGER,
    content_hash TEXT,                               -- SHA-256 for dedup (mirror aihousekeeper_attachments)
    raw_text TEXT,                                   -- pasted text or model-extracted text
    draft_json TEXT,                                 -- AI-extracted structured draft (JSON) for user review before commit
    error TEXT,
    created_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS savings_import_jobs_household_idx ON savings_import_jobs(household_id);
