/**
 * Brand-generic corpus primitives — the parts of a scale corpus that have
 * nothing to do with which tables a brand ledgers.
 *
 * WHY THIS EXISTS RATHER THAN A SECOND COPY INSIDE house-ledger-factory.ts
 * -----------------------------------------------------------------------
 * The PRNG, the watermark-map builder, the fingerprint and the clone are
 * identical for every brand and their whole contract is "produce the same bytes
 * forever". Two copies would drift the moment one is touched.
 *
 * WHY `ledger-factory.ts` (Budget) STILL HAS ITS OWN COPIES
 * --------------------------------------------------------
 * Deliberate, and the opposite call from §3.1's "promote, don't fork" — for a
 * reason specific to fixtures. Budget has a PUBLISHED baseline whose identity is
 * `corpusFingerprint()`, a sha256 over a generated corpus. Any edit to that file
 * that changed a single generated byte would invalidate every committed Budget
 * number, and `compare` would (correctly) refuse to grade against it. A frozen
 * fixture helper is the one kind of code where "do not touch it" beats "share
 * it". Budget adopts this module the next time it re-baselines; until then the
 * duplication is the safe direction.
 */

export type CorpusRow = Record<string, unknown>;

/** The only thing these helpers need to know about a brand's registry. */
export type CorpusRegistry<TName extends string> = {
  tableNames: readonly TName[];
  tableKeys: Readonly<Record<TName, string>>;
};

// ---------------------------------------------------------------------------
// seeded PRNG — no Date.now(), no Math.random(), identical on every host
// ---------------------------------------------------------------------------

/** mulberry32 — 32-bit, no state outside the closure. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function hashString(text: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i += 1) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/**
 * Seeded per (table, index) rather than per run, so a row's content depends
 * only on where it sits — generation stays reproducible even if the table
 * order or the loop shape ever changes.
 */
export function rngFor(seed: number, table: string, index: number): () => number {
  return mulberry32((hashString(table) ^ Math.imul(index + 1, 2654435761) ^ seed) >>> 0);
}

export function pick<T>(r: () => number, list: readonly T[]): T {
  return list[Math.floor(r() * list.length)]!;
}

export function chance(r: () => number, p: number): boolean {
  return r() < p;
}

export function pad2(n: number): string {
  return String(n).padStart(2, '0');
}

/** Device suffix `hlc.ts#format` embeds — last 7 chars of the device id. */
export function hlcSuffix(deviceId: string): string {
  return deviceId.slice(-7);
}

// ---------------------------------------------------------------------------
// the watermark map — the thing that makes a corpus "a household that SYNCED"
// ---------------------------------------------------------------------------

/**
 * Wall-clock window corpus watermarks are stamped in. Every corpus stamp sits
 * BELOW the wall clock the phases use for incoming ops (1.8e12 and up), so a
 * peer edit still wins the merge — the corpus is history, not the future.
 */
export const LWW_EPOCH = 1_600_000_000_000;

export type LwwMap = Record<string, Record<string, { f: Record<string, string> }>>;

/**
 * One `encodeStamp` per FIELD per row.
 *
 * `lww: {}` is the one value a household that has ever synced definitely does
 * NOT have, and with it every persist / AEAD / cold-open figure is understated.
 * For House this matters more than it did for Budget: `tasks` carries ~58
 * columns, so a task row alone costs ~58 stamps of ~40 bytes — the N5 wide-row
 * hazard (plan §1.6) is invisible without this map, and it is precisely the
 * decision H10 exists to inform.
 *
 * ⚠️ THE STAMP VALUES ARE NOT WHAT `applyLedgerDelta` PRODUCES. This used to
 * claim they were ("what `applyLedgerDelta` leaves behind after the create op
 * that materialized the row"); they are not. The merge core computes ONE
 * `encoded` string per op and writes that same string across every field the op
 * touched (`projection.ts`: `const encoded = encodeStamp(stamp)` then
 * `for (const field of Object.keys(rowDelta.f)) meta.f[field] = encoded`). A
 * created row therefore carries N copies of ONE stamp; distinct stamps per row
 * equal the number of distinct OPS that ever wrote it, not its column count.
 * This generator instead ticks a fresh HLC per field, so every stamp in the
 * corpus is unique.
 *
 * The COUNT and the char SIZE are right, so every byte figure — `disk.total`,
 * `coldopen.rows.lww.chars`, `mutate.lww.bytesPerStamp` — remains a valid floor.
 * DISTINCTNESS is wrong, and distinctness is the only property stamp interning
 * can exploit, so this map makes the He10 §4 mitigation "stamp interning" look
 * ~4x weaker than it is. Measured on the 10y corpus: the compact envelope form
 * cuts the plaintext 16% against these stamps and 64% against one-stamp-per-op.
 * Left as-is on purpose — correcting it changes the corpus fingerprint of a
 * GATED artefact, which is a decision for the harness owner, not a side effect
 * of a perf pass. Neither reading passes the Exit gate.
 *
 * NOT modelled: `del` tombstone stamps and `p` parked orphan patches. Both only
 * ADD, so the corpus is a floor.
 */
export function buildLwwMap<TName extends string>(
  ledger: Record<string, unknown>,
  registry: CorpusRegistry<TName>,
  ctx: { members: readonly string[]; devices: readonly string[] },
): LwwMap {
  const lww: LwwMap = {};
  const people = Math.max(1, ctx.members.length);
  let tick = 0;

  for (const table of registry.tableNames) {
    const keyField = registry.tableKeys[table];
    const forTable: Record<string, { f: Record<string, string> }> = {};
    const rows = (ledger[table] ?? []) as CorpusRow[];
    for (let i = 0; i < rows.length; i += 1) {
      const row = rows[i]!;
      const who = i % people;
      const suffix = hlcSuffix(ctx.devices[who] ?? ctx.devices[0]!);
      const member = ctx.members[who]!;
      const f: Record<string, string> = {};
      for (const field of Object.keys(row)) {
        const wall = LWW_EPOCH + (tick % 5_000_000) * 1000;
        f[field] =
          `${String(wall).padStart(15, '0')}-${(tick & 0xffff).toString(16).padStart(4, '0')}-${suffix}` +
          `|${member}`;
        tick += 1;
      }
      forTable[String(row[keyField])] = { f };
    }
    lww[table] = forTable;
  }
  return lww;
}

/** Field stamps in the watermark map — the number the N5 decision turns on. */
export function lwwStampCountOf(lww: unknown): number {
  let n = 0;
  const map = (lww ?? {}) as Record<string, Record<string, { f?: Record<string, string> }>>;
  for (const forTable of Object.values(map)) {
    for (const meta of Object.values(forTable ?? {})) n += Object.keys(meta.f ?? {}).length;
  }
  return n;
}

// ---------------------------------------------------------------------------
// generic ledger utilities
// ---------------------------------------------------------------------------

export function totalRowsOf<TName extends string>(
  ledger: Record<string, unknown>,
  registry: CorpusRegistry<TName>,
): number {
  let n = 0;
  for (const table of registry.tableNames) n += ((ledger[table] ?? []) as CorpusRow[]).length;
  return n;
}

export function rowIdAtOf<TName extends string>(
  ledger: Record<string, unknown>,
  registry: CorpusRegistry<TName>,
  table: TName,
  index: number,
): string {
  const rows = (ledger[table] ?? []) as CorpusRow[];
  const row = rows[((index % rows.length) + rows.length) % rows.length]!;
  return String(row[registry.tableKeys[table]]);
}

/**
 * A delete delta over `count` DISTINCT keys spread across the table — what a
 * bulk purge really emits. `planTableStrategy` routes anything touching
 * >= LEDGER_INDEX_THRESHOLD rows to the indexed cursor, so a 200-key delete is
 * ONE `rows.filter` at flush, not 200 whole-table rebuilds. Measuring it is the
 * only honest way to report it.
 */
export function bulkDeleteDeltaOf<TName extends string>(
  ledger: Record<string, unknown>,
  registry: CorpusRegistry<TName>,
  table: TName,
  count: number,
  offset = 0,
): { v: 1; d: Record<string, string[]> } {
  const rows = (ledger[table] ?? []) as CorpusRow[];
  const keyField = registry.tableKeys[table];
  const keys: string[] = [];
  const seen = new Set<string>();
  for (let i = 0; keys.length < count && i < rows.length; i += 1) {
    const key = String(rows[(offset + i) % rows.length]![keyField]);
    if (seen.has(key)) continue;
    seen.add(key);
    keys.push(key);
  }
  return { v: 1, d: { [table]: keys } };
}

/**
 * Deep-ish clone for peer-side measurements: every table array, every row AND
 * the whole watermark map, so an in-place mutator on one ledger cannot be seen
 * by the other. `ops` is shared by reference on purpose — the byte buffers are
 * immutable here and copying tens of thousands of them would dominate setup.
 *
 * The watermark map must be COPIED, not reset: `wins()` short-circuits on a
 * missing stamp, so a peer merging against `{}` is not running the merge the
 * product runs.
 */
export function cloneLedgerOf<TName extends string, TLedger extends Record<string, unknown>>(
  ledger: TLedger,
  registry: CorpusRegistry<TName>,
): TLedger {
  const copy = { ...ledger, conflicts: [] } as TLedger;
  for (const table of registry.tableNames) {
    (copy as Record<string, unknown>)[table] = ((ledger[table] ?? []) as CorpusRow[]).map((row) => ({
      ...row,
    }));
  }
  const lww = (ledger.lww ?? {}) as LwwMap;
  const copiedLww: LwwMap = {};
  for (const [table, forTable] of Object.entries(lww)) {
    const rows: Record<string, { f: Record<string, string> }> = {};
    for (const [key, meta] of Object.entries(forTable ?? {})) {
      rows[key] = { ...meta, f: { ...meta.f } };
    }
    copiedLww[table] = rows;
  }
  (copy as Record<string, unknown>).lww = copiedLww;
  return copy;
}
