import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';

import { households, users, householdMembers } from './schema';

// ============ SAVINGS & REGISTERED ACCOUNTS ============
// Columns match backend/migrations/0067_savings_tables.sql EXACTLY.
// Note: NOT re-exported from schema.ts — this domain uses hand-written SQL
// migrations (db:generate is intentionally bypassed), mirroring the budget domain.

export const savingsCategories = sqliteTable(
  'savings_categories',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    icon: text('icon'),
    color: text('color'),
    is_essential: integer('is_essential', { mode: 'boolean' }).notNull().default(false),
    sort_order: integer('sort_order').default(0),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({ household_idx: index('savings_categories_household_idx').on(t.household_id) })
);

export const savingsIncomeEntries = sqliteTable(
  'savings_income_entries',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    member_id: text('member_id').references(() => householdMembers.id, { onDelete: 'set null' }),
    source_type: text('source_type').notNull(),
    label: text('label').notNull(),
    amount_cents: integer('amount_cents').notNull(),
    income_date: text('income_date').notNull(),
    currency: text('currency').notNull().default('CAD'),
    notes: text('notes'),
    // logical FK → savingsIncomeTemplates.id; set when generated by applying a template (Phase 4)
    template_id: text('template_id'),
    // 'YYYY-MM' when generated by applying a template; NULL for ad-hoc income
    period: text('period'),
    // Provenance: 'manual' | 'ai_import' | 'history_import' | 'rollover'. Historical
    // (previous-years) AI imports stamp 'history_import' + import_batch_id.
    // 'rollover' = auto-generated draft copy of last month's confirmed regular
    // income (see workers/savings-income-rollover-worker.ts).
    source: text('source').notNull().default('manual'),
    import_batch_id: text('import_batch_id'), // groups one history-import commit; NULL for manual
    // 'draft' | 'confirmed'. Rollover-generated rows start 'draft' until the
    // member confirms (or edits+saves, which implicitly confirms — see
    // SavingsService.updateIncome). Every other creation path defaults straight
    // to 'confirmed'.
    status: text('status').notNull().default('confirmed'),
    // logical FK → savings_income_entries.id — the prior-month entry this draft
    // was rolled forward from. NULL for everything except 'rollover' rows.
    rolled_over_from_entry_id: text('rolled_over_from_entry_id'),
    created_by: text('created_by').references(() => users.id, { onDelete: 'set null' }),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
    updated_at: text('updated_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({
    household_idx: index('savings_income_household_idx').on(t.household_id),
    date_idx: index('savings_income_date_idx').on(t.household_id, t.income_date),
    import_batch_idx: index('savings_income_import_batch_idx').on(t.import_batch_id),
    status_idx: index('savings_income_status_idx').on(t.household_id, t.status),
  })
);

export const savingsSpendingEntries = sqliteTable(
  'savings_spending_entries',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    category_id: text('category_id').references(() => savingsCategories.id, { onDelete: 'set null' }),
    label: text('label').notNull(),
    amount_cents: integer('amount_cents').notNull(),
    currency: text('currency').notNull().default('CAD'),
    spending_date: text('spending_date').notNull(),
    notes: text('notes'),
    // logical FK → savingsRecurringPayments.id (plain TEXT to avoid migration table-order coupling)
    recurring_payment_id: text('recurring_payment_id'),
    // 'YYYY-MM' when generated by applying a recurring payment; NULL for ad-hoc spend
    period: text('period'),
    created_by: text('created_by').references(() => users.id, { onDelete: 'set null' }),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
    updated_at: text('updated_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({
    household_idx: index('savings_spending_household_idx').on(t.household_id),
    date_idx: index('savings_spending_date_idx').on(t.household_id, t.spending_date),
  })
);

export const savingsIncomeTemplates = sqliteTable(
  'savings_income_templates',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    member_id: text('member_id').references(() => householdMembers.id, { onDelete: 'set null' }),
    source_type: text('source_type').notNull(),
    label: text('label').notNull(),
    amount_cents: integer('amount_cents').notNull(),
    currency: text('currency').notNull().default('CAD'),
    day_of_month: integer('day_of_month'),
    active: integer('active', { mode: 'boolean' }).notNull().default(true),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({ household_idx: index('savings_income_templates_household_idx').on(t.household_id) })
);

export const savingsGoals = sqliteTable(
  'savings_goals',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    type: text('type').notNull(), // 'emergency_fund' | 'custom'
    name: text('name').notNull(),
    target_amount_cents: integer('target_amount_cents').notNull(),
    current_amount_cents: integer('current_amount_cents').notNull().default(0),
    target_date: text('target_date'),
    months_of_expenses: integer('months_of_expenses'),
    monthly_allocation_cents: integer('monthly_allocation_cents'),
    currency: text('currency').notNull().default('CAD'),
    status: text('status').notNull().default('active'), // 'active' | 'achieved' | 'archived'
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
    updated_at: text('updated_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({ household_idx: index('savings_goals_household_idx').on(t.household_id) })
);

export const registeredAccounts = sqliteTable(
  'registered_accounts',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    member_id: text('member_id').references(() => householdMembers.id, { onDelete: 'set null' }),
    // 'tfsa' | 'rrsp' | 'fhsa' | 'dpsp' | 'rpp'. A group/workplace RRSP stays
    // 'rrsp' with is_employer_plan = true; 'dpsp'/'rpp' are employer DC plans
    // that generate a Pension Adjustment reducing next year's personal RRSP room.
    account_type: text('account_type').notNull(),
    institution: text('institution'),
    // Workplace-plan metadata (migration 0076). is_employer_plan flags group RRSP /
    // DPSP / DC-RPP; employer_name is a display label for the sponsoring employer.
    is_employer_plan: integer('is_employer_plan', { mode: 'boolean' }).notNull().default(false),
    employer_name: text('employer_name'),
    balance_cents: integer('balance_cents').notNull().default(0),
    starting_room_cents: integer('starting_room_cents'),
    annual_limit_override_cents: integer('annual_limit_override_cents'),
    regular_contribution_cents: integer('regular_contribution_cents'),
    // Personal yearly contribution target (distinct from the CRA annual_limit_override).
    // Backs the per-account goal bar; progress counts self + employer contributions.
    annual_goal_cents: integer('annual_goal_cents'),
    // Goal expressed as a % of the room base (migration 0082). Mutually exclusive with
    // annual_goal_cents: when set, the effective goal $ is derived server-side from the
    // room. Backs the "% of room" goal option in the simple Pension flow.
    annual_goal_pct: integer('annual_goal_pct'),
    // Room-only placeholder (migration 0081): the Pension "Room" tab lets a household set
    // a member's contribution room (RRSP/TFSA) via just starting_room_cents, with no
    // balance/institution/transactions. Flagged so the client hides it from the Accounts
    // tab; cleared once the row gains real account detail. In the simple flow a room-only
    // line may also carry a goal, recurring contribution + employer match (migration 0082).
    is_room_only: integer('is_room_only', { mode: 'boolean' }).notNull().default(false),
    // Automatic monthly employer match (migration 0082): a recurring employer-funded
    // contribution materialized alongside the member's own regular_contribution_cents.
    employer_match_cents: integer('employer_match_cents'),
    // 'YYYY-MM' anchor for recurring backfill (migration 0082): the first month the
    // recurring contribution / employer match applies from.
    recurring_start_month: text('recurring_start_month'),
    room_as_of_date: text('room_as_of_date'),
    prior_earned_income_cents: integer('prior_earned_income_cents'),
    pension_adjustment_cents: integer('pension_adjustment_cents'),
    currency: text('currency').notNull().default('CAD'),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
    updated_at: text('updated_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({ household_idx: index('registered_accounts_household_idx').on(t.household_id) })
);

export const registeredTransactions = sqliteTable(
  'registered_transactions',
  {
    id: text('id').primaryKey(),
    account_id: text('account_id')
      .notNull()
      .references(() => registeredAccounts.id, { onDelete: 'cascade' }),
    type: text('type').notNull(), // 'contribution' | 'withdrawal'
    kind: text('kind').notNull().default('manual'), // 'regular' | 'manual' (recurrence provenance)
    // Who funded this contribution (migration 0076). Orthogonal to `kind`: drives the
    // self-vs-employer split in room/goal math. Employer contributions to a group RRSP
    // still consume the member's RRSP room; DPSP/RPP employer amounts feed the PA.
    contributor: text('contributor').notNull().default('self'), // 'self' | 'employer'
    amount_cents: integer('amount_cents').notNull(),
    transaction_date: text('transaction_date').notNull(),
    tax_year: integer('tax_year'),
    period: text('period'), // 'YYYY-MM' for auto-generated regular contributions; NULL for ad-hoc
    notes: text('notes'),
    // Provenance for undo parity with expenses/income (migration 0076): an AI statement
    // import stamps 'ai_import' + a shared import_batch_id so the batch can be reversed.
    source: text('source').notNull().default('manual'), // 'manual' | 'ai_import'
    import_batch_id: text('import_batch_id'),
    created_by: text('created_by').references(() => users.id, { onDelete: 'set null' }),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({
    account_idx: index('registered_transactions_account_idx').on(t.account_id),
    import_batch_idx: index('registered_transactions_import_batch_idx').on(t.import_batch_id),
  })
);

export const savingsRecurringPayments = sqliteTable(
  'savings_recurring_payments',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    category_id: text('category_id').references(() => savingsCategories.id),
    label: text('label').notNull(),
    amount_cents: integer('amount_cents').notNull(),
    currency: text('currency').notNull().default('CAD'),
    day_of_month: integer('day_of_month'),
    group_label: text('group_label'),
    is_essential: integer('is_essential', { mode: 'boolean' }).notNull().default(false),
    active: integer('active', { mode: 'boolean' }).notNull().default(true),
    // Autopay — when true, the household never needs a due-day reminder for
    // this payment, so `day_of_month` is forced to NULL alongside it (both on
    // create and whenever an update flips this to true) rather than left to
    // go stale next to a due day nothing will ever check.
    is_automated: integer('is_automated', { mode: 'boolean' }).notNull().default(false),
    // Month scope (migration 0151) — 'all_year' (default) runs the payment every
    // month of every year, matching all prior behavior. 'custom_months' restricts
    // it to `active_months` (JSON array of 1-12) for `scope_year` ONLY; every
    // other year still runs all 12 months, since a payment that started or ended
    // mid-year is a one-time correction for that year, not a seasonal repeat.
    scope_type: text('scope_type').notNull().default('all_year'), // 'all_year' | 'custom_months'
    scope_year: integer('scope_year'),
    active_months: text('active_months'), // JSON array of 1-12, only when scope_type='custom_months'
    source: text('source').notNull().default('manual'), // 'manual' | 'ai_import'
    created_by: text('created_by').references(() => users.id, { onDelete: 'set null' }),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
    updated_at: text('updated_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({ household_idx: index('savings_recurring_payments_household_idx').on(t.household_id) })
);

/**
 * Per-month savings target backing the Projection tab (migration 0117). Past
 * months are ACTUAL (derived from income − expenses, never stored here); this
 * table only holds the forward-looking intent for the current + remaining
 * months. `target_cents` may be negative — a planned deficit month is a valid
 * projection. "No target" is the ABSENCE of a row, not a 0.
 */
export const savingsMonthlyTargets = sqliteTable(
  'savings_monthly_targets',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    period: text('period').notNull(), // 'YYYY-MM'
    target_cents: integer('target_cents').notNull(),
    currency: text('currency').notNull().default('CAD'),
    created_by: text('created_by').references(() => users.id, { onDelete: 'set null' }),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
    updated_at: text('updated_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({
    household_idx: index('savings_monthly_targets_household_idx').on(t.household_id, t.period),
  })
);

/**
 * Household-wide default for which Projection method drives Home / the
 * widget / the Watch (migration 0172). One row per household — a member
 * changing it changes what every member and every surface sees, unlike a
 * per-user preference. Absence of a row means 'hybrid' (the recommended
 * default), so most households never write here at all.
 */
export const savingsProjectionSettings = sqliteTable('savings_projection_settings', {
  household_id: text('household_id')
    .primaryKey()
    .references(() => households.id, { onDelete: 'cascade' }),
  default_method: text('default_method').notNull().default('hybrid'), // 'historical_average' | 'trend' | 'planned_budget' | 'hybrid'
  updated_by: text('updated_by').references(() => users.id, { onDelete: 'set null' }),
  updated_at: text('updated_at')
    .notNull()
    .default(sql`(datetime('now'))`),
});

export const savingsImportJobs = sqliteTable(
  'savings_import_jobs',
  {
    id: text('id').primaryKey(),
    household_id: text('household_id')
      .notNull()
      .references(() => households.id, { onDelete: 'cascade' }),
    // pending_upload | uploaded | analyzing | ready | committed | failed
    status: text('status').notNull().default('pending_upload'),
    source_kind: text('source_kind').notNull(), // 'file' | 'image' | 'text' | 'drive'
    file_key: text('file_key'),
    file_name: text('file_name'),
    mime_type: text('mime_type'),
    size_bytes: integer('size_bytes'),
    content_hash: text('content_hash'),
    raw_text: text('raw_text'),
    draft_json: text('draft_json'),
    error: text('error'),
    created_by: text('created_by').references(() => users.id, { onDelete: 'set null' }),
    created_at: text('created_at')
      .notNull()
      .default(sql`(datetime('now'))`),
    updated_at: text('updated_at')
      .notNull()
      .default(sql`(datetime('now'))`),
  },
  (t) => ({ household_idx: index('savings_import_jobs_household_idx').on(t.household_id) })
);

// Export types
export type SavingsCategory = typeof savingsCategories.$inferSelect;
export type NewSavingsCategory = typeof savingsCategories.$inferInsert;
export type SavingsIncomeEntry = typeof savingsIncomeEntries.$inferSelect;
export type NewSavingsIncomeEntry = typeof savingsIncomeEntries.$inferInsert;
export type SavingsSpendingEntry = typeof savingsSpendingEntries.$inferSelect;
export type NewSavingsSpendingEntry = typeof savingsSpendingEntries.$inferInsert;
export type SavingsIncomeTemplate = typeof savingsIncomeTemplates.$inferSelect;
export type NewSavingsIncomeTemplate = typeof savingsIncomeTemplates.$inferInsert;
export type SavingsGoal = typeof savingsGoals.$inferSelect;
export type NewSavingsGoal = typeof savingsGoals.$inferInsert;
export type SavingsRecurringPayment = typeof savingsRecurringPayments.$inferSelect;
export type NewSavingsRecurringPayment = typeof savingsRecurringPayments.$inferInsert;
export type SavingsImportJob = typeof savingsImportJobs.$inferSelect;
export type NewSavingsImportJob = typeof savingsImportJobs.$inferInsert;
export type SavingsMonthlyTarget = typeof savingsMonthlyTargets.$inferSelect;
export type NewSavingsMonthlyTarget = typeof savingsMonthlyTargets.$inferInsert;
export type SavingsProjectionSettings = typeof savingsProjectionSettings.$inferSelect;
export type NewSavingsProjectionSettings = typeof savingsProjectionSettings.$inferInsert;
export type RegisteredAccount = typeof registeredAccounts.$inferSelect;
export type NewRegisteredAccount = typeof registeredAccounts.$inferInsert;
export type RegisteredTransaction = typeof registeredTransactions.$inferSelect;
export type NewRegisteredTransaction = typeof registeredTransactions.$inferInsert;
