// GENERATED by scripts/build-tokens.mjs (APP_BRAND=symply-budget) — DO NOT EDIT.
// Sources: brands/_shared/tokens.base.json + brands/symply-budget/tokens.json
// Run: APP_BRAND=symply-budget npm run design:build
// Shared spacing, radii, typography, fonts.

export const spacing = {
  "xxs": 2,
  "xs": 4,
  "sm": 8,
  "smd": 10,
  "md": 12,
  "base": 16,
  "lg": 20,
  "xl": 24,
  "xxl": 32
} as const;

export const radii = {
  "xs": 4,
  "sm": 8,
  "md": 12,
  "lg": 16,
  "xl": 20,
  "full": 9999
} as const;

export const typography = {
  "display": {
    "size": 34,
    "weight": "700",
    "lineHeight": 41,
    "letterSpacing": -0.5
  },
  "heading": {
    "size": 28,
    "weight": "600",
    "lineHeight": 34,
    "letterSpacing": -0.3
  },
  "title": {
    "size": 24,
    "weight": "600",
    "lineHeight": 30
  },
  "body": {
    "size": 16,
    "weight": "400",
    "lineHeight": 22
  },
  "caption": {
    "size": 13,
    "weight": "400",
    "lineHeight": 18
  }
} as const;

export const fonts = {
  "family": {
    "regular": "System",
    "medium": "System",
    "bold": "System"
  },
  "nativeDesign": "default"
} as const;
