import {
  healthApi,
  HEALTH_ACTIVITY_PREFERENCE_FLAGS,
  type HealthActivityPreferenceFlag,
  type HealthActivityPreferenceFlags,
} from '@api/health';
import { storageHelpers } from '@services/storage';

import { readThrough } from './healthRepository';

/**
 * Symply Health — the ACTIVITY NOTIFICATION preferences (donor
 * `ActivityNotificationPreferencesView`).
 *
 * Record of truth: `PUT /health/activity-preferences` on the
 * `symply-health-api` Worker (`backend/src/routes/health-body-extras.ts`). Ten
 * booleans have been deployed there since P2 with, until this module, zero
 * callers — the screen that owned them in the donor was never ported, so the
 * only way to change them was a hand-written request.
 *
 * MMKV is an offline read-through cache exactly as in every other Health store,
 * never the record (see `healthRepository`).
 *
 * ## What these switches DO and DO NOT do today — read before changing the copy
 *
 * They are stored, they are per-account, and they sync across the member's
 * devices. They do NOT yet gate a send: nothing on this Worker reads them (grep
 * `receive_push_notifications` outside the route + schema and you find only
 * tests), because the donor features that produce these events — family recipe
 * sharing, shared workout videos, shared progress photos, the buddy community —
 * are not part of the Symply Health port.
 *
 * That is why {@link HEALTH_NOTIFICATION_GROUPS} carries a `disclosure` string
 * per group and the screen renders it. A settings screen that silently implies
 * "turn this off and we will stop sending you X" when nothing sends X is the
 * kind of quiet lie this app does not ship. The switches are still real: the
 * member's choice is recorded now and applies the moment a producer lands.
 */

/* ==================================================================== */
/* Cache key                                                             */
/* ==================================================================== */

/**
 * MUST be registered in `healthCacheKeys.ts` (it is) — these flags are an
 * account-level preference, so a copy left behind on sign-out would show the
 * next person on the handset the previous member's choices.
 */
export const HEALTH_NOTIFY_PREFS_KEY = 'health.notifyPrefs.v1';

/* ==================================================================== */
/* Defaults + shape                                                      */
/* ==================================================================== */

export type HealthNotificationPreferences = HealthActivityPreferenceFlags;

/**
 * Mirrors `ACTIVITY_PREFERENCE_DEFAULTS` in
 * `backend/src/services/health-body-extras-service.ts` (donor migration 074)
 * EXACTLY. The Worker returns these for an account that has never saved, so a
 * different set here would make the screen flicker from one truth to another as
 * the network answers.
 */
export const DEFAULT_HEALTH_NOTIFICATION_PREFERENCES: HealthNotificationPreferences = {
  notify_recipe_created: true,
  notify_recipe_updated: false,
  notify_custom_food_created: true,
  notify_workout_video_shared: true,
  notify_photo_shared: true,
  notify_milestone_achieved: true,
  // Community traffic is opt-IN — it is the one class generated by strangers.
  notify_community_recipe_created: false,
  notify_community_achievement: false,
  receive_push_notifications: true,
  receive_inapp_notifications: true,
};

export interface HealthNotificationToggle {
  flag: HealthActivityPreferenceFlag;
  title: string;
  description: string;
  /** Brand-kit icon name (see `brands/symply-health/src/assets/icons`). */
  icon: string;
}

export interface HealthNotificationGroup {
  id: 'delivery' | 'sharing' | 'community';
  title: string;
  /** Honest statement of what this group can and cannot do today. May be null. */
  disclosure: string | null;
  toggles: HealthNotificationToggle[];
}

/**
 * The donor's own three sections (`Delivery Method` / `Family Activities` /
 * `Community Activities`), with titles and descriptions carried over and the
 * icons mapped onto the Symply Health kit.
 */
export const HEALTH_NOTIFICATION_GROUPS: readonly HealthNotificationGroup[] = [
  {
    id: 'delivery',
    title: 'How we reach you',
    disclosure:
      'Symply Health sends reminders you set up yourself. These two switches decide where they arrive.',
    toggles: [
      {
        flag: 'receive_push_notifications',
        title: 'Push notifications',
        description: 'Alerts on this device, even when the app is closed',
        icon: 'notifications',
      },
      {
        flag: 'receive_inapp_notifications',
        title: 'In-app notifications',
        description: 'Show them in the app when you open it',
        icon: 'reminders',
      },
    ],
  },
  {
    id: 'sharing',
    title: 'Sharing with family',
    disclosure:
      'Symply Health has no family sharing yet, so nothing sends these today. Your choices are saved to your account and apply as soon as it lands.',
    toggles: [
      {
        flag: 'notify_recipe_created',
        title: 'New recipes',
        description: 'When someone in your family shares a recipe',
        icon: 'recipe',
      },
      {
        flag: 'notify_recipe_updated',
        title: 'Recipe updates',
        description: 'When a shared recipe changes',
        icon: 'edit',
      },
      {
        flag: 'notify_custom_food_created',
        title: 'Custom foods',
        description: 'When someone adds a food to the shared library',
        icon: 'food-search',
      },
      {
        flag: 'notify_workout_video_shared',
        title: 'Workout videos',
        description: 'When someone shares a workout video',
        icon: 'workout-library',
      },
      {
        flag: 'notify_photo_shared',
        title: 'Progress photos',
        description: 'When someone shares a progress photo',
        icon: 'progress-compare',
      },
      {
        flag: 'notify_milestone_achieved',
        title: 'Milestones',
        description: 'When someone reaches a goal they were tracking',
        icon: 'goals',
      },
    ],
  },
  {
    id: 'community',
    title: 'Community',
    disclosure:
      'The community is not part of Symply Health yet. Both start switched off, and nothing is sent until you turn them on.',
    toggles: [
      {
        flag: 'notify_community_recipe_created',
        title: 'Community recipes',
        description: 'When people you follow share a recipe',
        icon: 'members',
      },
      {
        flag: 'notify_community_achievement',
        title: 'Community milestones',
        description: 'When people you follow reach a goal',
        icon: 'streak',
      },
    ],
  },
];

/** Every flag that is NOT a delivery switch — i.e. the per-event toggles. */
export const HEALTH_ACTIVITY_EVENT_FLAGS: readonly HealthActivityPreferenceFlag[] =
  HEALTH_NOTIFICATION_GROUPS.filter((group) => group.id !== 'delivery').flatMap((group) =>
    group.toggles.map((toggle) => toggle.flag)
  );

/* ==================================================================== */
/* Read / write                                                          */
/* ==================================================================== */

function coerce(value: unknown): HealthNotificationPreferences {
  const source = (value ?? {}) as Partial<Record<HealthActivityPreferenceFlag, unknown>>;
  const prefs = { ...DEFAULT_HEALTH_NOTIFICATION_PREFERENCES };
  for (const flag of HEALTH_ACTIVITY_PREFERENCE_FLAGS) {
    // The Worker stores INTEGER 0/1 and answers booleans; a cached snapshot from
    // an older build (or a hand-edited one) can be anything at all. Anything
    // that is not a boolean falls back to the donor default rather than being
    // coerced, so a truthy `1` cannot masquerade as a deliberate choice.
    if (typeof source[flag] === 'boolean') prefs[flag] = source[flag] as boolean;
  }
  return prefs;
}

async function fetchNotificationPreferences(): Promise<HealthNotificationPreferences> {
  const payload = await healthApi.activityPreferences();
  return coerce(payload?.preferences);
}

/** Read-through: the cache renders instantly, a successful read replaces it. */
export async function loadNotificationPreferences(): Promise<HealthNotificationPreferences> {
  const prefs = await readThrough(HEALTH_NOTIFY_PREFS_KEY, fetchNotificationPreferences, {
    ...DEFAULT_HEALTH_NOTIFICATION_PREFERENCES,
  });
  return coerce(prefs);
}

export interface HealthNotificationWriteResult {
  preferences: HealthNotificationPreferences;
  status: 'saved' | 'offline';
  /** Friendly copy, or null when there is nothing to say. Never a raw error. */
  message: string | null;
}

export const NOTIFY_PREFS_OFFLINE_MESSAGE =
  'Saved on this device — we will sync it to your account when you are back online.';

/**
 * PATCH one or more flags.
 *
 * Only the changed keys are sent: the route merges server-side, so a client
 * that posted the whole object would overwrite a flag a newer build knows about
 * and this one does not.
 */
export async function saveNotificationPreferences(
  patch: Partial<HealthNotificationPreferences>
): Promise<HealthNotificationWriteResult> {
  const before = await loadNotificationPreferences();
  const optimistic = coerce({ ...before, ...patch });
  try {
    const payload = await healthApi.saveActivityPreferences(patch);
    const preferences = coerce(payload?.preferences ?? optimistic);
    await storageHelpers.setObject(HEALTH_NOTIFY_PREFS_KEY, preferences);
    return { preferences, status: 'saved', message: null };
  } catch {
    // The member's own choice is kept and shown back to them: this is a
    // preference, not a health record, and the next successful read replaces the
    // cache wholesale. No error string ever reaches the UI.
    await storageHelpers.setObject(HEALTH_NOTIFY_PREFS_KEY, optimistic);
    return { preferences: optimistic, status: 'offline', message: NOTIFY_PREFS_OFFLINE_MESSAGE };
  }
}

/** Donor's "Reset to Defaults" — sends all ten explicitly, never a bare PUT. */
export async function resetNotificationPreferences(): Promise<HealthNotificationWriteResult> {
  return saveNotificationPreferences({ ...DEFAULT_HEALTH_NOTIFICATION_PREFERENCES });
}

/** One-line summary for the "More" row subtitle. */
export function describeNotificationPreferences(prefs: HealthNotificationPreferences): string {
  const delivery = prefs.receive_push_notifications
    ? 'Push on'
    : prefs.receive_inapp_notifications
      ? 'In-app only'
      : 'All off';
  const on = HEALTH_ACTIVITY_EVENT_FLAGS.filter((flag) => prefs[flag]).length;
  return `${delivery} · ${on} of ${HEALTH_ACTIVITY_EVENT_FLAGS.length} activity alerts`;
}
