import { useFocusEffect } from 'expo-router/react-navigation';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Alert,
  StyleSheet,
  TouchableOpacity,
  useWindowDimensions,
  View,
} from 'react-native';
import { ScrollView } from 'react-native-gesture-handler';
import { PieChart } from 'react-native-gifted-charts';

import {
  budgetApi,
  type BudgetCategory,
  type BudgetEncouragement,
  type MonthlyOverview,
} from '@api/budget';
import { homeBudgetApi } from '@api/home-budget';
import {
  savingsApi,
  type SavingsOverview,
  type SavingsProjection,
  type SavingsTrendPoint,
} from '@api/savings';
import { ScreenScrollEnd, screenScrollEndTestId } from '@components/common';
import { ResponsiveLayout } from '@components/layout/ResponsiveLayout';
import { Button, Card, Typography } from '@components/ui';
import { ActivityIndicator } from '@components/ui/ActivityIndicator';
import { AppBarChart } from '@components/ui/AppBarChart';
import { Icon } from '@components/ui/Icon';
import { useTheme } from '@contexts/ThemeContext';
import { isMinimalBudget } from '@features/budget';
import { useBudgetSnapshotPublisher } from '@features/budget/budgetSnapshot';
import { countedCategoryRows } from '@features/budget/bulk/bulkOverview';
import { useBudgetInsights } from '@features/budget/insights/useBudgetInsights';
import { budgetLocalUnsupportedCopyFromError } from '@features/budget/local/ai/localAiUnsupported';
import { BudgetLocalNotReadyError } from '@features/budget/local/errors';
import { useBudgetStore } from '@stores/budgetStore';
import { useHouseholdStore } from '@stores/householdStore';
import { useSavingsStore } from '@stores/savingsStore';
import { useAppColors } from '@theme';
import { categoryRampColor } from '@theme/chartPalette';
import { getBudgetCategoryIcon } from '@utils/budgetCategoryIcon';
import { useDisplayCurrency } from '@utils/money';

import { BudgetEnrolmentBanner } from './BudgetEnrolmentBanner';
import { formatBudgetCurrency as formatCurrency } from './budgetFormat';
import {
  BUDGET_STICKY_HEADER_INDICES,
  BUDGET_STICKY_SCROLL_CONTENT,
  BudgetMonthHeader,
  monthLabel,
  monthName,
  monthYearLabel,
  shiftMonth,
} from './BudgetMonthHeader';
import { BudgetPlannedFitCard } from './BudgetPlannedFitCard';
import { PROJECTION_METHOD_LABELS } from './savings/SavingsProjectionView';
import { SavingsTrendChart, type SavingsTrendChartTab } from './SavingsTrendChart';

export { categoryRampColor };

/** Gifted Charts crashes when PieChart's first slice or BarChart rules get 0/Infinity. */
export function buildDonutSlices(
  spent: number,
  remaining: number,
  plannedBudget: number,
  spentColor: string,
  remainingColor: string,
): Array<{ value: number; color: string }> {
  const slices: Array<{ value: number; color: string }> = [];
  if (spent > 0) slices.push({ value: spent, color: spentColor });
  if (remaining > 0) slices.push({ value: remaining, color: remainingColor });
  if (slices.length === 0 && plannedBudget > 0) {
    return [{ value: plannedBudget, color: remainingColor }];
  }
  return slices;
}

/**
 * Days still to be funded in the `{year, month}` period, counting today as one
 * of them: a member opening the app on the 12th of a 30-day month has 19 days
 * (63%) of budget still ahead. A month already over has 0 (0%); a month not yet
 * started has all of its days (100%). `month` is 1-based like every other
 * period arg on this screen.
 */
export function remainingDaysInMonth(
  year: number,
  month: number,
  today: Date = new Date(),
): { days: number; total: number; percent: number } {
  const total = new Date(year, month, 0).getDate();
  const selected = year * 12 + (month - 1);
  const current = today.getFullYear() * 12 + today.getMonth();
  let days: number;
  if (selected < current) days = 0;
  else if (selected > current) days = total;
  else days = total - today.getDate() + 1;
  return { days, total, percent: Math.round((days / total) * 100) };
}

export interface CategorySpendRow {
  id: string;
  name: string;
  color: string;
  amount: number;
  share: number;
  /**
   * The real category ids folded into an aggregate row — set only on 'other',
   * so the drill-down can reassemble the same bucket the row is showing.
   * Absent on rows that ARE a category (their own `id` is the bucket).
   */
  categoryIds?: string[];
}

/** Longest failure reason worth putting in an alert — enough to identify it, short enough to read. */
const MAX_FAILURE_REASON_CHARS = 160;

/**
 * Insights are generated by the member's own AI provider on local-first, so a
 * refresh can fail for reasons only the provider knows: a rejected key, a
 * retired model, no network. "Please try again" alone hides all three behind
 * the same dead end — append what the failure actually said. Provider errors
 * are scrubbed of anything key-shaped before they reach here.
 */
export function insightsFailureMessage(error: unknown): string {
  const base = 'Could not generate insights right now. Please try again.';
  const reason = error instanceof Error ? error.message.trim() : '';
  if (!reason) return base;
  const trimmed =
    reason.length > MAX_FAILURE_REASON_CHARS
      ? `${reason.slice(0, MAX_FAILURE_REASON_CHARS)}…`
      : reason;
  return `${base}\n\n${trimmed}`;
}

/**
 * The local ledger has not opened yet — a cold-launch phase, not a failure.
 *
 * `useHouseholdStore` rehydrates its persisted `currentHousehold` before
 * `ensureBudgetLocalSession` opens the engine, so the first focus fires all four
 * loaders below against an empty session map. Every one of them throws, and
 * logging that as an error says a load failed when nothing has been tried yet:
 * on an iPhone 13 (2026-09-03) one cold launch wrote 12 such lines in a second.
 *
 * Staying quiet is safe because the recovery is already wired — the focus effect
 * lists `currentHousehold?.id` in its deps, and opening the session republishes
 * the store with the ledger's own household id, which re-runs every loader.
 */
function isLocalSessionNotReady(error: unknown): boolean {
  return error instanceof BudgetLocalNotReadyError;
}

const UNCategorized = {
  id: 'uncategorized',
  name: 'Uncategorized',
};

/**
 * Category chart color for a given rank — a tint of the brand teal that gets
 * progressively lighter for smaller slices, so the donut, progress bars, and
 * icon chips read as one cohesive color family (same hue as the primary accent)
 * instead of clashing per-category hues. Fully derived from the passed teal
 * token; returns a solid `#RRGGBB` so callers can still append an alpha suffix.
 */
/** Aggregate month expenses into ranked category rows (top N + Other). */
export function buildCategorySpendingRows(
  expenses: Array<{ category_id: string | null; amount: number }>,
  categories: Array<{
    id: string;
    name: string;
    icon: string | null;
    color: string | null;
  }>,
  baseColor: string,
  maxRows = 5,
): CategorySpendRow[] {
  if (expenses.length === 0) return [];

  const totals = new Map<string, number>();
  for (const expense of expenses) {
    const key = expense.category_id ?? UNCategorized.id;
    totals.set(key, (totals.get(key) ?? 0) + expense.amount);
  }

  const totalSpent = [...totals.values()].reduce(
    (sum, amount) => sum + amount,
    0,
  );
  if (totalSpent <= 0) return [];

  const categoryById = new Map(categories.map(cat => [cat.id, cat]));

  const rows: CategorySpendRow[] = [...totals.entries()].map(([id, amount]) => {
    const category = id === UNCategorized.id ? null : categoryById.get(id);
    return {
      id,
      name: category?.name ?? UNCategorized.name,
      color: baseColor, // replaced by the teal ramp once ranked
      amount,
      share: amount / totalSpent,
    };
  });

  rows.sort((a, b) => b.amount - a.amount);

  let ranked: CategorySpendRow[];
  if (rows.length <= maxRows) {
    ranked = rows;
  } else {
    const folded = rows.slice(maxRows - 1);
    const otherAmount = folded.reduce((sum, row) => sum + row.amount, 0);
    ranked = [
      ...rows.slice(0, maxRows - 1),
      {
        id: 'other',
        name: 'Other',
        color: baseColor,
        amount: otherAmount,
        share: otherAmount / totalSpent,
        categoryIds: folded.map(row => row.id),
      },
    ];
  }

  // Recolor the ranked rows as one cohesive teal family — strongest teal for the
  // largest slice, lighter tints down the ranking.
  return ranked.map((row, index) => ({
    ...row,
    color: categoryRampColor(baseColor, index),
  }));
}

interface Props {
  year: number;
  month: number;
  onMonthChange: (year: number, month: number) => void;
  /** Edit a planned item straight from the "Planned spending fit" card. */
  onEditPlannedItem?: (itemId: string) => void;
  /**
   * Drill into a category's product breakdown + trends. Also fires for the
   * aggregate 'other' row, which hands over `row.categoryIds` instead of one id.
   */
  onCategoryPress?: (row: CategorySpendRow) => void;
  /** Jump to Savings → Goals. Omitted when the savings feature is disabled. */
  onOpenGoals?: () => void;
  /** Open the "Add income" entry form. Omitted when the savings feature is disabled. */
  onAddIncome?: () => void;
  /**
   * Tapping "Savings this month" jumps to Savings → Overview. Omitted when the
   * savings feature is disabled.
   */
  onOpenSavingsOverview?: () => void;
  /**
   * Tapping "Projected year-end" jumps to Savings → Projection. Omitted when
   * the savings feature is disabled.
   */
  onOpenProjection?: () => void;
}

export function BudgetDashboardView({
  year,
  month,
  onMonthChange,
  onEditPlannedItem,
  onCategoryPress,
  onOpenGoals,
  onAddIncome,
  onOpenSavingsOverview,
  onOpenProjection,
}: Props) {
  const { theme } = useTheme();
  const { width: windowWidth } = useWindowDimensions();
  const colors = useAppColors();
  const { currentHousehold } = useHouseholdStore();
  const { dataRevision, insightsDirtyHids, clearInsightsDirty } = useBudgetStore();
  // IP5: the headroom card must refresh on BOTH budget and savings mutations.
  const savingsDataRevision = useSavingsStore(s => s.dataRevision);

  const [overview, setOverview] = useState<MonthlyOverview | null>(null);
  const [savingsOverview, setSavingsOverview] =
    useState<SavingsOverview | null>(null);
  // Full-year projection under the household's default method (Projection tab
  // → "Set as household default"). Same gating as savingsOverview — hidden
  // when the savings feature is unavailable.
  const [projection, setProjection] = useState<SavingsProjection | null>(null);
  const [encouragement, setEncouragement] =
    useState<BudgetEncouragement | null>(null);
  const [categories, setCategories] = useState<BudgetCategory[]>([]);
  const [trend, setTrend] = useState<
    Array<{ year: number; month: number; spent: number }>
  >([]);
  // Savings cashflow trend (income/spending/net per month). Null when the
  // savings feature is unavailable (minimal budget / 404) — the trend card then
  // falls back to the budget-only spending bars with no series selector.
  const [savingsTrend, setSavingsTrend] = useState<SavingsTrendPoint[] | null>(
    null,
  );
  const [trendMode, setTrendMode] = useState<SavingsTrendChartTab>('chart-savings');

  // Prior month's net savings, looked up from the already-loaded cashflow trend
  // (not a second fetch) — feeds the widget's "vs last month" savings trend.
  const savingsPreviousCents = useMemo(() => {
    const { year: py, month: pm } = shiftMonth(year, month, 1);
    const previousPeriod = `${py}-${String(pm).padStart(2, '0')}`;
    return savingsTrend?.find(p => p.period === previousPeriod)?.net;
  }, [savingsTrend, year, month]);

  // Settings → Currency. Subscribed (not read imperatively) for two reasons:
  // `formatCurrency` below reads the store outside React, so without this the
  // whole dashboard keeps rendering the old symbol until some unrelated state
  // change forces a re-render; and it is what re-runs the publisher effect so
  // the widget/watch snapshots follow the preference.
  const displayCurrency = useDisplayCurrency();

  // Feed the iOS home-screen widget and the Apple Watch companion. This is the
  // only writer for both App Group keys: the previous writer (BudgetHomeScreen)
  // is never mounted for the Budget brand, so both surfaces rendered their empty
  // state permanently. Matrix: BUDGET-WIDGET-001, BUDGET-WATCH-001.
  useBudgetSnapshotPublisher(overview, {
    periodLabel: `${monthLabel(month)} ${year}`,
    // Neither surface can read the store — omitting this left the widget on its
    // USD fallback ("US$2,000") and the watch on the device locale, no matter
    // what the member picked in Settings. Matrix: BUDGET-WIDGET-021.
    currency: displayCurrency,
    savingsCurrentCents: savingsOverview?.netSavings,
    savingsPreviousCents,
    projectedYearEndCents: projection?.projectedYearEnd,
    insightTone: encouragement?.tone,
    insightMessage: encouragement?.message,
    insightEmoji: encouragement?.emoji,
  });
  const [isLoading, setIsLoading] = useState(true);

  // Insights follow the overview: `useBudgetInsights` fingerprints the month and
  // regenerates only when those numbers actually move (see the hook's header for
  // the fingerprint / debounce / single-flight / stale-guard rules). The card
  // used to force a regeneration on every focus and every `dataRevision` bump,
  // which is why a sync burst rewrote it several times in a row.
  const {
    insights,
    loading: insightsLoading,
    refresh: refreshInsights,
  } = useBudgetInsights({
    householdId: currentHousehold?.id,
    year,
    month,
    overview,
    enabled: !isMinimalBudget(),
    onRefreshError: (error: unknown) => {
      const offlineCopy = budgetLocalUnsupportedCopyFromError(error, 'insights');
      Alert.alert(
        offlineCopy?.title ?? 'Insights unavailable',
        offlineCopy?.message ?? insightsFailureMessage(error),
      );
    },
  });

  const loadOverview = useCallback(async () => {
    if (!currentHousehold?.id) return;
    try {
      if (isMinimalBudget()) {
        const data = await homeBudgetApi.getMonthlyOverview(
          currentHousehold.id,
          year,
          month,
        );
        setOverview(data);
        setCategories([]);
        setEncouragement(null);
        return;
      }
      const [data, categoryRes, encouragementRes] = await Promise.all([
        budgetApi.getMonthlyOverview(currentHousehold.id, year, month),
        budgetApi.getCategories(currentHousehold.id),
        // Non-critical — a failure here must never blank the overview.
        budgetApi
          .getEncouragement(currentHousehold.id, year, month)
          .catch(() => null),
      ]);
      setOverview(data);
      setCategories(categoryRes.categories);
      setEncouragement(encouragementRes);
    } catch (error) {
      if (isLocalSessionNotReady(error)) return;
      console.error('Error loading monthly overview:', error);
    }
  }, [currentHousehold?.id, year, month]);

  // Savings summary — BE-computed netSavings. Hidden when savings navigation
  // is unavailable (minimal budget / feature disabled).
  const loadSavingsHeadroom = useCallback(async () => {
    if (!onOpenGoals || !currentHousehold?.id || isMinimalBudget()) return;
    try {
      const data = await savingsApi.getOverview(
        currentHousehold.id,
        year,
        month,
      );
      setSavingsOverview(data);
    } catch (error) {
      if (isLocalSessionNotReady(error)) return;
      const status = (error as { response?: { status?: number } })?.response
        ?.status;
      if (status === 404) {
        setSavingsOverview(null); // feature disabled — hide the card
      } else {
        console.error('Error loading savings headroom:', error);
      }
    }
  }, [currentHousehold?.id, year, month, onOpenGoals]);

  // Year-end projection under the household's default method — feeds the
  // "Projected year-end" stat here and the widget/Watch snapshot below. Gated
  // exactly like the headroom card; a 404 hides the stat.
  const projectionGeneration = React.useRef(0);
  const loadProjection = useCallback(async () => {
    const generation = ++projectionGeneration.current;
    if (!onOpenGoals || !currentHousehold?.id || isMinimalBudget()) return;
    try {
      const data = await savingsApi.getProjection(currentHousehold.id, year);
      if (generation !== projectionGeneration.current) return;
      setProjection(data);
    } catch (error) {
      if (generation !== projectionGeneration.current) return;
      if (isLocalSessionNotReady(error)) return;
      const status = (error as { response?: { status?: number } })?.response
        ?.status;
      if (status === 404) {
        setProjection(null);
      } else {
        console.error('Error loading savings projection:', error);
      }
    }
  }, [currentHousehold?.id, year, onOpenGoals]);

  // Savings cashflow trend — the coherent income/spending/net triple (spending
  // here INCLUDES recurring Monthly Payments, so net = income − spending). Gated
  // exactly like the headroom card; a 404 hides the series selector.
  const loadSavingsTrend = useCallback(async () => {
    if (!onOpenGoals || !currentHousehold?.id || isMinimalBudget()) {
      setSavingsTrend(null);
      return;
    }
    try {
      // Current year only: Jan → the selected month (getTrend walks back
      // `months` inclusively, so a span of `month` lands on January).
      const data = await savingsApi.getTrend(
        currentHousehold.id,
        year,
        month,
        month,
      );
      setSavingsTrend(data.months);
    } catch (error) {
      if (isLocalSessionNotReady(error)) return;
      const status = (error as { response?: { status?: number } })?.response
        ?.status;
      if (status === 404) {
        setSavingsTrend(null); // feature disabled — spending-only fallback
      } else {
        console.error('Error loading savings trend:', error);
      }
    }
  }, [currentHousehold?.id, year, month, onOpenGoals]);

  const loadTrend = useCallback(async () => {
    if (!currentHousehold?.id) return;
    // Current year only: January → the selected month.
    const months = Array.from({ length: month }, (_, i) => ({
      year,
      month: i + 1,
    }));
    try {
      const fetchOverview = isMinimalBudget()
        ? homeBudgetApi.getMonthlyOverview
        : budgetApi.getMonthlyOverview;
      const results = await Promise.all(
        months.map(m => fetchOverview(currentHousehold.id, m.year, m.month)),
      );
      setTrend(months.map((m, i) => ({ ...m, spent: results[i].actualSpent })));
    } catch (error) {
      if (isLocalSessionNotReady(error)) return;
      console.error('Error loading budget trend:', error);
    }
  }, [currentHousehold?.id, year, month]);

  useFocusEffect(
    useCallback(() => {
      setIsLoading(true);
      Promise.all([loadOverview(), loadTrend()]).finally(() =>
        setIsLoading(false),
      );
      void loadSavingsHeadroom();
      void loadSavingsTrend();
      void loadProjection();
      // Focus reloads the month's DATA; insights follow it only if the reload
      // actually changed something. The dirty flag is cleared (it is per-member
      // bookkeeping that would otherwise pile up), but it no longer forces a
      // generation — the fingerprint is a better answer to the same question,
      // and it is right for peer syncs and restores too.
      const hid = currentHousehold?.id;
      if (hid && insightsDirtyHids[hid]) clearInsightsDirty(hid);
    }, [
      loadOverview,
      loadTrend,
      loadSavingsHeadroom,
      loadSavingsTrend,
      loadProjection,
      currentHousehold?.id,
      insightsDirtyHids,
      clearInsightsDirty,
    ]),
  );

  // Drop savings UI when the parent omits savings navigation (minimal budget).
  useEffect(() => {
    if (!onOpenGoals) {
      setSavingsOverview(null);
      setSavingsTrend(null);
      setProjection(null);
    }
  }, [onOpenGoals]);

  // A mutation landed (this member's edit, a chat action, or a peer op merged by
  // the sync bridge). Reload the month — insights re-read the reloaded overview
  // and stay put unless its fingerprint moved. This effect used to force an AI
  // regeneration here, which is how one sync burst became a burst of model calls.
  useEffect(() => {
    if (dataRevision === 0) return;
    void loadOverview();
    void loadTrend();
  }, [dataRevision, loadOverview, loadTrend]);

  // IP5 (CRITICAL): refresh the savings headroom card after either a budget OR a
  // savings mutation, without a remount. Both revisions are listed in the deps.
  useEffect(() => {
    void loadSavingsHeadroom();
    void loadSavingsTrend();
    void loadProjection();
  }, [
    dataRevision,
    savingsDataRevision,
    loadSavingsHeadroom,
    loadSavingsTrend,
    loadProjection,
  ]);

  const chartWidth = Math.max(200, windowWidth - 96);
  const categoryLayoutColumn = windowWidth < 420;

  const donutData = useMemo(() => {
    if (!overview || overview.plannedBudget <= 0) return [];
    const spent = Math.max(0, overview.actualSpent + overview.committedTotal);
    const remaining = Math.max(0, overview.remainingBudget);
    return buildDonutSlices(
      spent,
      remaining,
      overview.plannedBudget,
      theme.pastel.teal,
      colors.borderColor,
    );
  }, [overview, theme, colors.borderColor]);

  // Deliberately not memoised: it reads the wall clock, and every focus
  // re-renders this screen through load(), so a day rolling over while the app
  // sits in the background is picked up the next time the member looks.
  const remainingDays = remainingDaysInMonth(year, month);

  const barData = useMemo(
    () =>
      trend.map(t => ({
        value: t.spent / 100,
        label: monthLabel(t.month),
        frontColor:
          t.year === year && t.month === month
            ? colors.primary
            : theme.pastel.teal,
      })),
    [trend, year, month, theme, colors.primary],
  );

  // Savings accumulated so far this year (in cents): the running sum of net
  // savings across the shown months (Jan → the selected month). A past month
  // with income but zero logged expenses is skipped — that combination means
  // spending was never tracked that month (e.g. backfilled income with no
  // matching entries), not that the household spent nothing, so counting it
  // would overstate the total. A month with no income still counts (its flat
  // monthly-payment obligations are real either way — mirrors the backend's
  // ytdNet). The last point (the month being viewed) always counts — it's a
  // "so far" figure, so no spending logged yet is expected, not missing data.
  const accumulatedNet = useMemo(() => {
    if (!savingsTrend) return null;
    return savingsTrend.reduce((sum, p, i) => {
      const isViewedMonth = i === savingsTrend.length - 1;
      const isOneSidedBackfill = p.income !== 0 && !p.hasExpenseData;
      if (isOneSidedBackfill && !isViewedMonth) return sum;
      return sum + p.net;
    }, 0);
  }, [savingsTrend]);

  // How many earlier months were left out of accumulatedNet for lacking
  // expense data — surfaced next to the figure so it reads as "partial", not
  // silently wrong.
  const accumulatedNetExcludedMonths = useMemo(() => {
    if (!savingsTrend) return 0;
    return savingsTrend.reduce((count, p, i) => {
      const isViewedMonth = i === savingsTrend.length - 1;
      const isOneSidedBackfill = p.income !== 0 && !p.hasExpenseData;
      return isOneSidedBackfill && !isViewedMonth ? count + 1 : count;
    }, 0);
  }, [savingsTrend]);

  // Category roll-up on the month lens: a stock-up contributes its portion, and
  // portions reserved from earlier months land under their own category.
  const categorySpending = useMemo(
    () =>
      buildCategorySpendingRows(
        countedCategoryRows(overview),
        categories,
        theme.pastel.teal,
      ),
    [overview, categories, theme.pastel.teal],
  );

  const categoryDonutData = useMemo(
    () =>
      categorySpending.map(row => ({
        value: row.amount,
        color: row.color,
      })),
    [categorySpending],
  );

  return (
    <ScrollView
      testID="budget-dashboard"
      style={styles.scroll}
      contentContainerStyle={BUDGET_STICKY_SCROLL_CONTENT}
      showsVerticalScrollIndicator={false}
      stickyHeaderIndices={BUDGET_STICKY_HEADER_INDICES}
    >
      {/* Sticky index 0 — month stepper stays pinned while the rest of the
          dashboard scrolls beneath it. Shared with Spending/Savings/Pension so
          the header's metrics can't drift per screen (see BudgetMonthHeader). */}
      <BudgetMonthHeader
        label={monthYearLabel(year, month)}
        onPrev={() => {
          const prev = shiftMonth(year, month, 1);
          onMonthChange(prev.year, prev.month);
        }}
        onNext={() => {
          const next = shiftMonth(year, month, -1);
          onMonthChange(next.year, next.month);
        }}
        prevTestID="budget-month-prev"
        nextTestID="budget-month-next"
        labelTestID="budget-dashboard-month-label"
      />

      {/* Only the main content swaps to a spinner while loading — the month
          selector above stays statically mounted; the add row below is hidden
          until the data resolves so the CTAs never flash over the spinner. */}
      {isLoading ? (
        <View style={styles.loadingContainer} testID="budget-dashboard-loading">
          <ActivityIndicator size="large" color={theme.pastel.teal} />
        </View>
      ) : (
        // Reading-width cap + centering on iPad — without it this single
        // column of cards stretches edge-to-edge on wide screens (a
        // stretched-iPhone layout, not a real iPad adaptation). No-op on
        // phone widths (ResponsiveLayout only constrains when isTablet).
        <ResponsiveLayout maxWidth={700} centerContent padding={0}>
          {/* No sync banner and no encouragement banner on Home — deliberately.
              Both used to sit here, and between them they pushed the numbers a
              member opens the app to read below the fold on a phone. The sync
              panel in particular is transient by nature: it reappears on every
              pass, so on an established household it reads as noise rather than
              as news, and the one state that IS news — "this device is still
              owed the household's history" — now lives where a member goes to
              act on it, on the Sync screen beside `Download full household
              history`, rather than on a screen with no control to press.
              `BudgetSyncProgressPanel` still renders on Sync, Join and Invite. */}

          {/* The ONE exception to the paragraph above, and it clears every bar
              that argument sets. Not transient: `awaitingEnrolment` is a stuck
              state, not a per-pass event, so it cannot reappear as noise. Not a
              cost to an established household: it renders `null` for every
              enrolled device, so nothing moves below the fold in the ordinary
              case. Not a screen with no control to press: it goes to Device
              Sync, which is the act that ends it.

              And the "it lives where the member goes to act on it" premise is
              the one thing that does NOT hold here. A member whose device is
              unenrolled has no reason to open Sync — they are looking at their
              real household, marked Active, showing an empty budget, and the
              reasonable conclusion is that their data is gone. The numbers this
              dashboard protects are all zero and cannot be fixed by anything
              they type, so there is nothing left to push below the fold. */}
          <BudgetEnrolmentBanner />

          {/* Remaining balance */}
          <Card variant="filled" style={styles.balanceCard}>
            {overview && overview.plannedBudget > 0 && donutData.length > 0 ? (
              <View style={styles.balanceRow}>
                <PieChart
                  data={donutData}
                  donut
                  radius={70}
                  innerRadius={46}
                  innerCircleColor={colors.backgroundSecondary}
                  centerLabelComponent={() => (
                    <View style={styles.pieCenter}>
                      <Typography
                        variant="caption2"
                        color={colors.textSecondary}
                      >
                        Left
                      </Typography>
                      <Typography
                        variant="body"
                        weight="bold"
                        color={
                          overview.remainingBudget < 0
                            ? colors.error
                            : colors.textPrimary
                        }
                      >
                        {formatCurrency(overview.remainingBudget)}
                      </Typography>
                    </View>
                  )}
                />
                <View style={styles.balanceDetails}>
                  <BalanceRow
                    label="Budget"
                    value={formatCurrency(overview.plannedBudget)}
                  />
                  <BalanceRow
                    label="Spent"
                    value={formatCurrency(overview.actualSpent)}
                    testID="budget-dashboard-spent-value"
                  />
                  <BalanceRow
                    label="Committed"
                    value={formatCurrency(overview.committedTotal)}
                  />
                  <BalanceRow
                    label="Remaining"
                    value={formatCurrency(overview.remainingBudget)}
                    emphasize
                    negative={overview.remainingBudget < 0}
                  />
                  <BalanceRow
                    label="Remaining days"
                    value={`${remainingDays.days} (${remainingDays.percent}%)`}
                    color={colors.orange}
                    testID="budget-dashboard-remaining-days"
                  />
                </View>
              </View>
            ) : (
              <View style={styles.noBudget}>
                <Typography
                  variant="body"
                  color={colors.textSecondary}
                  align="center"
                >
                  {!isMinimalBudget()
                    ? `No budget set for ${monthYearLabel(
                        year,
                        month,
                      )}. Set a monthly cap in Settings to see your remaining balance.`
                    : `No budget set for ${monthYearLabel(year, month)}.`}
                </Typography>
              </View>
            )}
          </Card>

          {/* Savings summary — BE-computed netSavings. Hidden when the savings
          feature is disabled (404 → savingsOverview stays null). */}
          {onOpenGoals && savingsOverview && (
            <Card
              variant="filled"
              style={styles.savingsCard}
              testID="budget-savings-headroom"
            >
              <View style={styles.savingsTitleRow}>
                <Typography variant="title3" weight="semibold">
                  Savings summary
                </Typography>
                <TouchableOpacity
                  onPress={() =>
                    Alert.alert(
                      'Savings summary',
                      '“Savings this month” is your income this month minus your recurring monthly payments and everything you spent.' +
                        (projection
                          ? ` “Projected ${projection.year} year-end” extrapolates that using your household's ${projection.forecast?.scenarios.find((s) => s.method === projection.method)?.label ?? PROJECTION_METHOD_LABELS[projection.method]} ${projection.forecast ? 'scenario' : 'method'} — change it any time from Savings → Projection.`
                          : ''),
                      [{ text: 'Got it' }]
                    )
                  }
                  hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                  accessibilityRole="button"
                  accessibilityLabel="What do these savings figures mean?"
                  testID="budget-savings-headroom-info"
                >
                  <Icon
                    name="information-circle-outline"
                    size={18}
                    color={colors.textSecondary}
                  />
                </TouchableOpacity>
              </View>
              {savingsOverview.income.total !== 0 ? (
                <View style={styles.savingsRow}>
                  <SavingsStatCell
                    label="Savings this month"
                    value={formatCurrency(savingsOverview.netSavings)}
                    negative={savingsOverview.netSavings < 0}
                    onPress={onOpenSavingsOverview}
                    accessibilityLabel="Open savings overview"
                    testID="budget-savings-open-overview"
                  />
                  {projection && (
                    <SavingsStatCell
                      label={`Projected ${projection.year} year-end`}
                      value={formatCurrency(projection.projectedYearEnd)}
                      negative={projection.projectedYearEnd < 0}
                      onPress={onOpenProjection}
                      accessibilityLabel="Open savings projection"
                      testID="budget-savings-projected-year-end"
                    />
                  )}
                </View>
              ) : (
                // No income logged for the month — netSavings is meaningless
                // (would just show the expense total as "negative savings"),
                // so prompt to add income instead of showing a scary red number.
                <View style={styles.savingsNoIncome}>
                  <Typography variant="body" color={colors.textSecondary}>
                    {`Add your income for ${monthName(month)} to see your savings for this month.`}
                  </Typography>
                  {onAddIncome && (
                    <Button
                      title="Add income"
                      size="sm"
                      variant="outline"
                      onPress={onAddIncome}
                      style={styles.savingsAddIncomeButton}
                      testID="budget-savings-add-income"
                    />
                  )}
                </View>
              )}
            </Card>
          )}

          {/* Planned spending fit — full Budget brand only. */}
          {!isMinimalBudget() && overview && overview.plannedBudget > 0 && (
            <BudgetPlannedFitCard
              overview={overview}
              year={year}
              month={month}
              onEditItem={onEditPlannedItem}
            />
          )}

          {/* Spend / saving trend. With the savings feature active the card
              shows the shared Savings / Spending / Monthly chart (the SAME
              component the Savings screen's Overview tab renders); otherwise
              it falls back to spending only. */}
          <Card variant="filled" style={styles.chartCard}>
            <View style={styles.trendHeader}>
              <View style={styles.trendHeaderText}>
                <Typography
                  variant="title3"
                  weight="semibold"
                  style={styles.chartTitle}
                >
                  {savingsTrend ? 'Cashflow trend' : 'Spending trend'}
                </Typography>
                <Typography
                  variant="caption1"
                  color={colors.textSecondary}
                  style={styles.chartSubtitle}
                >
                  {month === 1
                    ? `${monthLabel(1)} ${year}`
                    : `${monthLabel(1)}–${monthLabel(month)} ${year}`}
                </Typography>
              </View>
              {/* Savings accumulated so far this year = running sum of the net
                  savings shown (Jan → the selected month). */}
              {accumulatedNet !== null && (
                <View style={styles.trendAccrued} testID="budget-trend-accrued">
                  <Typography variant="caption1" color={colors.textSecondary}>
                    Saved so far
                  </Typography>
                  <Typography
                    variant="title3"
                    weight="bold"
                    color={accumulatedNet < 0 ? colors.error : theme.pastel.teal}
                  >
                    {formatCurrency(accumulatedNet)}
                  </Typography>
                </View>
              )}
            </View>
            {accumulatedNet !== null && accumulatedNetExcludedMonths > 0 && (
              <Typography
                variant="caption2"
                color={colors.textSecondary}
                align="right"
                style={styles.trendExcluded}
                testID="budget-trend-accrued-excluded"
              >
                excl. {accumulatedNetExcludedMonths}{' '}
                {accumulatedNetExcludedMonths === 1 ? 'month' : 'months'} w/o spend data
              </Typography>
            )}
            {savingsTrend ? (
              <SavingsTrendChart
                trend={savingsTrend}
                width={chartWidth}
                activeTab={trendMode}
                onTabChange={setTrendMode}
                showTitle={false}
                tabsStyle={styles.trendTabs}
                emptyLabel="No cashflow history yet."
              />
            ) : barData.length > 0 ? (
              <AppBarChart data={barData} width={chartWidth} />
            ) : (
              <Typography variant="body" color={colors.textSecondary}>
                No spending history yet.
              </Typography>
            )}
          </Card>

          {/* Spending by category */}
          <Card
            variant="filled"
            style={styles.chartCard}
            testID="budget-category-spending"
          >
            <View style={styles.categoryHeader}>
              <View style={styles.categoryHeaderText}>
                <Typography variant="title3" weight="semibold">
                  Spending by category
                </Typography>
                <Typography variant="caption1" color={colors.textSecondary}>
                  {monthName(month)} breakdown
                </Typography>
              </View>
              {overview && overview.actualSpent > 0 && (
                <Typography
                  variant="subheadline"
                  weight="semibold"
                  color={theme.pastel.teal}
                >
                  {formatCurrency(overview.actualSpent)}
                </Typography>
              )}
            </View>

            {categorySpending.length === 0 ? (
              <Typography variant="body" color={colors.textSecondary}>
                No spending recorded this month yet.
              </Typography>
            ) : (
              <View
                style={[
                  styles.categoryBody,
                  categoryLayoutColumn && styles.categoryBodyColumn,
                ]}
              >
                {categorySpending.length > 1 &&
                  categoryDonutData.length > 0 && (
                    <View style={styles.categoryDonutWrap}>
                      <PieChart
                        data={categoryDonutData}
                        donut
                        radius={52}
                        innerRadius={34}
                        innerCircleColor={colors.backgroundSecondary}
                      />
                    </View>
                  )}
                <View style={styles.categoryList}>
                  {categorySpending.map(row => (
                    // 'other' drills in like any other row — it carries the ids
                    // it folded, and the detail screen re-aggregates them.
                    <CategorySpendRowItem
                      key={row.id}
                      row={row}
                      onPress={onCategoryPress}
                    />
                  ))}
                </View>
              </View>
            )}
          </Card>

          {/* AI insights — full Budget brand only. */}
          {!isMinimalBudget() && (
            <Card variant="filled" style={styles.chartCard} testID="budget-insights-card">
              <View style={styles.insightsHeader}>
                <Typography variant="title3" weight="semibold">
                  Insights
                </Typography>
                <TouchableOpacity
                  onPress={refreshInsights}
                  disabled={insightsLoading}
                  testID="budget-insights-refresh"
                >
                  {insightsLoading ? (
                    <ActivityIndicator size="small" color={theme.pastel.teal} />
                  ) : (
                    <Typography variant="caption1" color={theme.pastel.teal}>
                      Refresh
                    </Typography>
                  )}
                </TouchableOpacity>
              </View>
              {insights ? (
                <>
                  {!!insights.summary && <Typography
                    variant="body"
                    style={styles.insightSummary}
                    testID="budget-insights-summary"
                  >
                    {insights.summary}
                  </Typography>}
                  {insights.alerts.map((alert, i) => (
                    <View key={i} style={styles.alertRow}>
                      <Icon
                        name={
                          alert.severity === 'critical'
                            ? 'alert-circle'
                            : alert.severity === 'warning'
                            ? 'warning'
                            : 'information-circle'
                        }
                        size={18}
                        color={
                          alert.severity === 'critical'
                            ? colors.error
                            : alert.severity === 'warning'
                            ? colors.warning
                            : colors.info
                        }
                      />
                      <Typography variant="caption1" style={styles.alertText}>
                        {alert.message}
                      </Typography>
                    </View>
                  ))}
                  {insights.recommendations.map((rec, i) => (
                    <View key={i} style={styles.alertRow}>
                      <Icon name="bulb" size={18} color={colors.warning} />
                      <Typography variant="caption1" style={styles.alertText}>
                        {rec}
                      </Typography>
                    </View>
                  ))}
                </>
              ) : (
                <Typography
                  variant="body"
                  color={colors.textSecondary}
                  testID="budget-insights-empty"
                >
                  {insightsLoading
                    ? 'Generating insights…'
                    : 'No insights yet.'}
                </Typography>
              )}
            </Card>
          )}
        </ResponsiveLayout>
      )}
      <ScreenScrollEnd testID={screenScrollEndTestId('budget-dashboard')} />
    </ScrollView>
  );
}

/**
 * One "Savings this month" / "Projected year-end" figure. Tappable when given
 * an `onPress` (jumps to the matching Savings sub-tab) — visually flagged with
 * a trailing chevron, the same affordance `CategorySpendRowItem` uses below,
 * so both "this is a number" and "this number is a link" read at a glance.
 */
function SavingsStatCell({
  label,
  value,
  negative,
  onPress,
  accessibilityLabel,
  testID,
}: {
  label: string;
  value: string;
  negative?: boolean;
  onPress?: () => void;
  accessibilityLabel?: string;
  testID?: string;
}) {
  const colors = useAppColors();
  const tappable = !!onPress;

  const content = (
    <>
      <View style={styles.savingsStatLabelRow}>
        <Typography variant="caption1" color={colors.textSecondary}>
          {label}
        </Typography>
        {tappable && (
          <Icon name="chevron-forward" size={14} color={colors.textTertiary} />
        )}
      </View>
      <Typography
        variant="title3"
        weight="bold"
        color={negative ? colors.chartNegative : colors.textPrimary}
      >
        {value}
      </Typography>
    </>
  );

  if (!tappable) {
    return (
      <View style={styles.savingsStat} testID={testID}>
        {content}
      </View>
    );
  }

  return (
    <TouchableOpacity
      style={styles.savingsStat}
      onPress={onPress}
      activeOpacity={0.6}
      hitSlop={{ top: 6, bottom: 6, left: 6, right: 6 }}
      accessibilityRole="button"
      accessibilityLabel={accessibilityLabel}
      testID={testID}
    >
      {content}
    </TouchableOpacity>
  );
}

function CategorySpendRowItem({
  row,
  onPress,
}: {
  row: CategorySpendRow;
  onPress?: (row: CategorySpendRow) => void;
}) {
  const colors = useAppColors();
  const sharePct = Math.round(row.share * 100);
  const tappable = !!onPress;

  const content = (
    <View style={styles.categoryRow}>
      <View style={styles.categoryRowTop}>
        <View style={styles.categoryRowLeft}>
          <View
            style={[
              styles.categoryIconChip,
              { backgroundColor: `${row.color}22` },
            ]}
          >
            <Icon
              name={getBudgetCategoryIcon(row.name)}
              size={18}
              color={row.color}
            />
          </View>
          <View style={styles.categoryRowLabels}>
            <Typography variant="body" weight="medium" numberOfLines={1}>
              {row.name}
            </Typography>
            <Typography variant="caption2" color={colors.textSecondary}>
              {sharePct}% of spending
            </Typography>
          </View>
        </View>
        <View style={styles.categoryRowRight}>
          <Typography variant="subheadline" weight="semibold">
            {formatCurrency(row.amount)}
          </Typography>
          {tappable && (
            <Icon
              name="chevron-forward"
              size={16}
              color={colors.textTertiary}
            />
          )}
        </View>
      </View>
      <View
        style={[styles.categoryTrack, { backgroundColor: colors.borderColor }]}
      >
        <View
          style={[
            styles.categoryFill,
            {
              width: `${Math.max(sharePct, row.amount > 0 ? 4 : 0)}%`,
              backgroundColor: row.color,
            },
          ]}
        />
      </View>
    </View>
  );

  if (!tappable) return content;

  return (
    <TouchableOpacity
      activeOpacity={0.6}
      onPress={() => onPress?.(row)}
      testID={`budget-category-row-${row.id}`}
      accessibilityRole="button"
      accessibilityLabel={`View ${row.name} products and trends`}
    >
      {content}
    </TouchableOpacity>
  );
}

function BalanceRow({
  label,
  value,
  emphasize,
  negative,
  color,
  testID,
}: {
  label: string;
  value: string;
  emphasize?: boolean;
  negative?: boolean;
  /** Value colour when not `negative` (which always wins with the error red). */
  color?: string;
  testID?: string;
}) {
  const colors = useAppColors();
  return (
    <View style={styles.balanceDetailRow}>
      <Typography variant="caption1" color={colors.textSecondary}>
        {label}
      </Typography>
      <Typography
        variant={emphasize ? 'subheadline' : 'caption1'}
        weight={emphasize ? 'bold' : 'medium'}
        color={negative ? colors.error : color ?? colors.textPrimary}
        testID={testID}
      >
        {value}
      </Typography>
    </View>
  );
}

const styles = StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  loadingContainer: {
    paddingVertical: 60,
    alignItems: 'center',
  },
  balanceCard: {
    padding: 20,
    marginBottom: 16,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  pieCenter: {
    alignItems: 'center',
  },
  balanceDetails: {
    flex: 1,
    gap: 6,
  },
  balanceDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  noBudget: {
    paddingVertical: 12,
  },
  chartCard: {
    padding: 20,
    marginBottom: 16,
  },
  savingsCard: {
    padding: 20,
    marginBottom: 16,
  },
  savingsTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  savingsRow: {
    flexDirection: 'row',
    gap: 16,
  },
  savingsStat: {
    flex: 1,
    gap: 4,
  },
  savingsStatLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  savingsNoIncome: {
    gap: 12,
  },
  savingsAddIncomeButton: {
    alignSelf: 'flex-start',
  },
  chartTitle: {
    marginBottom: 4,
  },
  chartSubtitle: {
    marginBottom: 16,
  },
  trendHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  trendHeaderText: {
    flex: 1,
  },
  trendAccrued: {
    alignItems: 'flex-end',
    gap: 2,
  },
  trendExcluded: {
    marginTop: 4,
  },
  trendTabs: {
    marginBottom: 16,
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    gap: 12,
  },
  categoryHeaderText: {
    flex: 1,
    gap: 2,
  },
  categoryBody: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  categoryBodyColumn: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  categoryDonutWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryList: {
    flex: 1,
    gap: 14,
  },
  categoryRow: {
    gap: 8,
  },
  categoryRowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  categoryRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  categoryRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  categoryRowLabels: {
    flex: 1,
    gap: 2,
  },
  categoryIconChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryTrack: {
    height: 6,
    borderRadius: 999,
    overflow: 'hidden',
  },
  categoryFill: {
    height: '100%',
    borderRadius: 999,
    minWidth: 4,
  },
  insightsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  insightSummary: {
    marginBottom: 8,
  },
  alertRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
    alignItems: 'flex-start',
  },
  alertText: {
    flex: 1,
  },
});
