/**
 * `localGarbageApi` + the ported date expansion.
 *
 * The expansion fixtures below were GENERATED by running
 * `GarbageCollectionService.getNextCollectionDates`
 * (`backend/src/services/garbage-collection-service.ts:361`) verbatim under
 * `TZ=UTC`, then pasted here — this is the "ported server logic each has a unit
 * test asserting parity with the server implementation's fixtures" line of the
 * H3 DoD. They are timezone-stable because `expandCollectionDates` formats from
 * local calendar fields (see that file's header), so a device in UTC-7 gets the
 * same answers as the Worker rather than yesterday's.
 *
 * Static imports only — `await import()` throws under this Jest config (§6.2).
 */
import type { GarbageScheduleType } from '@api/garbage-collection';

import {
  getLocalHouseLedger,
  openLocalHouseSession,
  resetLocalHouseSession,
} from '../engine';
import { HouseLocalUnsupportedError } from '../errors';
import { HOUSE_LOCAL_GARBAGE_REMOTE_METHODS, localGarbageApi } from '../localGarbageApi';
import { expandCollectionDates } from '../logic/garbageSchedule';
import { getHouseUnsupportedCopy } from '../unsupportedCopy';

/** Monday 10 August 2026, before and after the 07:00 collection cut-off. */
const MONDAY_EARLY = new Date(2026, 7, 10, 6, 0, 0);
const MONDAY_LATE = new Date(2026, 7, 10, 9, 0, 0);

const USER = 'user-garbage-1';

async function freshSession() {
  await resetLocalHouseSession();
  return openLocalHouseSession({ userId: USER, displayName: 'Garbage home' });
}

function opCount(): number {
  return getLocalHouseLedger().ops.length;
}

const weekly = (type: GarbageScheduleType['type'], dayOfWeek: number): GarbageScheduleType => ({
  type,
  frequency: 'weekly',
  dayOfWeek,
});

describe('garbageSchedule expansion — parity with the Worker', () => {
  it('weekly: every occurrence of the day inside the window', () => {
    expect(expandCollectionDates([weekly('garbage', 3)], 30, MONDAY_EARLY)).toEqual([
      { date: '2026-08-12', types: ['garbage'] },
      { date: '2026-08-19', types: ['garbage'] },
      { date: '2026-08-26', types: ['garbage'] },
      { date: '2026-09-02', types: ['garbage'] },
      { date: '2026-09-09', types: ['garbage'] },
    ]);
  });

  it('weekly: keeps today before 07:00 and drops it after — the truck has been', () => {
    expect(expandCollectionDates([weekly('garbage', 1)], 21, MONDAY_EARLY)).toEqual([
      { date: '2026-08-10', types: ['garbage'] },
      { date: '2026-08-17', types: ['garbage'] },
      { date: '2026-08-24', types: ['garbage'] },
      { date: '2026-08-31', types: ['garbage'] },
    ]);

    expect(expandCollectionDates([weekly('garbage', 1)], 21, MONDAY_LATE)).toEqual([
      { date: '2026-08-17', types: ['garbage'] },
      { date: '2026-08-24', types: ['garbage'] },
      { date: '2026-08-31', types: ['garbage'] },
    ]);
  });

  it('biweekly: week B is offset seven days so A and B never collide', () => {
    const schedules: GarbageScheduleType[] = [
      { type: 'garbage', frequency: 'biweekly', dayOfWeek: 3, week: 'A' },
      { type: 'recycling', frequency: 'biweekly', dayOfWeek: 3, week: 'B' },
    ];
    expect(expandCollectionDates(schedules, 30, MONDAY_EARLY)).toEqual([
      { date: '2026-08-12', types: ['garbage'] },
      { date: '2026-08-19', types: ['recycling'] },
      { date: '2026-08-26', types: ['garbage'] },
      { date: '2026-09-02', types: ['recycling'] },
      { date: '2026-09-09', types: ['garbage'] },
    ]);
  });

  it('merges two streams that land on the same day into one entry', () => {
    expect(
      expandCollectionDates([weekly('garbage', 3), weekly('organics', 3)], 14, MONDAY_EARLY),
    ).toEqual([
      { date: '2026-08-12', types: ['garbage', 'organics'] },
      { date: '2026-08-19', types: ['garbage', 'organics'] },
    ]);
  });

  it('monthly: the Nth weekday of each month, skipping one already past', () => {
    const schedules: GarbageScheduleType[] = [
      { type: 'bulkItem', frequency: 'monthly', dayOfWeek: 6, weekOfMonth: [1, 3] },
    ];
    // August's first Saturday (the 1st) is behind us, so the run starts at the
    // third. The trailing 17 Oct is PAST the 60-day window: the server bounds
    // the loop on its month cursor, not on the pickup date, and the port keeps
    // that behaviour deliberately (see `logic/garbageSchedule.ts`).
    expect(expandCollectionDates(schedules, 60, MONDAY_EARLY)).toEqual([
      { date: '2026-08-15', types: ['bulkItem'] },
      { date: '2026-09-05', types: ['bulkItem'] },
      { date: '2026-09-19', types: ['bulkItem'] },
      { date: '2026-10-03', types: ['bulkItem'] },
      { date: '2026-10-17', types: ['bulkItem'] },
    ]);
  });

  it('monthly: defaults to the first week when weekOfMonth is absent', () => {
    expect(
      expandCollectionDates(
        [{ type: 'bulkItem', frequency: 'monthly', dayOfWeek: 2 }],
        40,
        MONDAY_EARLY,
      ),
    ).toEqual([{ date: '2026-09-01', types: ['bulkItem'] }]);
  });

  it('seasonal: collects inside the season and not outside it', () => {
    const inSeason: GarbageScheduleType[] = [
      {
        type: 'yardWaste',
        frequency: 'seasonal',
        dayOfWeek: 2,
        seasonStart: { month: 4, day: 1 },
        seasonEnd: { month: 11, day: 30 },
      },
    ];
    expect(expandCollectionDates(inSeason, 30, MONDAY_EARLY)).toEqual([
      { date: '2026-08-11', types: ['yardWaste'] },
      { date: '2026-08-18', types: ['yardWaste'] },
      { date: '2026-08-25', types: ['yardWaste'] },
      { date: '2026-09-01', types: ['yardWaste'] },
      { date: '2026-09-08', types: ['yardWaste'] },
    ]);

    const winterOnly: GarbageScheduleType[] = [
      {
        type: 'yardWaste',
        frequency: 'seasonal',
        dayOfWeek: 2,
        seasonStart: { month: 12, day: 1 },
        seasonEnd: { month: 2, day: 28 },
      },
    ];
    expect(expandCollectionDates(winterOnly, 30, MONDAY_EARLY)).toEqual([]);
  });

  it('on-request has no calendar, and neither does an empty schedule', () => {
    expect(
      expandCollectionDates([{ type: 'bulkItem', frequency: 'on-request' }], 30, MONDAY_EARLY),
    ).toEqual([]);
    expect(expandCollectionDates([], 30, MONDAY_EARLY)).toEqual([]);
    expect(expandCollectionDates(null, 30, MONDAY_EARLY)).toEqual([]);
  });

  it('skips a half-written stream instead of throwing the card down', () => {
    const schedules = [
      { frequency: 'weekly', dayOfWeek: 3 } as unknown as GarbageScheduleType,
      weekly('garbage', 3),
    ];
    expect(expandCollectionDates(schedules, 14, MONDAY_EARLY)).toEqual([
      { date: '2026-08-12', types: ['garbage'] },
      { date: '2026-08-19', types: ['garbage'] },
    ]);
  });

  it('clamps the window to 1..365, treating 0 as the 30-day default', () => {
    const thirtyDays = expandCollectionDates([weekly('garbage', 3)], 30, MONDAY_EARLY);
    expect(expandCollectionDates([weekly('garbage', 3)], 0, MONDAY_EARLY)).toEqual(thirtyDays);

    const clamped = expandCollectionDates([weekly('garbage', 3)], 9999, MONDAY_EARLY);
    expect(clamped).toHaveLength(52);
    expect(clamped[0]).toEqual({ date: '2026-08-12', types: ['garbage'] });
    expect(clamped[clamped.length - 1]).toEqual({ date: '2027-08-04', types: ['garbage'] });
  });
});

describe('localGarbageApi — Tier A schedule CRUD', () => {
  afterEach(async () => {
    await resetLocalHouseSession();
  });

  it('get-or-creates the row so callers always have a schedule id', async () => {
    const ledger = await freshSession();
    const { schedule } = await localGarbageApi.getSchedule(ledger.household.id);

    expect(schedule.id).toEqual(expect.any(String));
    expect(schedule.schedules).toEqual([]);
    expect(schedule.source).toBe('manual');
    // Column defaults ported from the service's insert.
    expect(schedule.set_out_time).toBe('19:00');
    expect(schedule.collection_start_time).toBe('07:00');
    expect(schedule.remove_by_time).toBe('19:00');
    expect(schedule.reminders).toEqual({
      nightBefore: { enabled: true, time: '19:00' },
      morningOf: { enabled: false, time: '07:00' },
    });

    // Second read is a pure read — no second row, no second op.
    const before = opCount();
    const again = await localGarbageApi.getSchedule(ledger.household.id);
    expect(again.schedule.id).toBe(schedule.id);
    expect(opCount()).toBe(before);
    expect(getLocalHouseLedger().garbageSchedules).toHaveLength(1);
  });

  it('createSchedule upserts onto the auto-created row rather than duplicating it', async () => {
    const ledger = await freshSession();
    const { schedule: seeded } = await localGarbageApi.getSchedule(ledger.household.id);

    const { schedule } = await localGarbageApi.createSchedule(ledger.household.id, {
      municipality: 'Burnaby',
      schedules: [weekly('garbage', 3)],
      set_out_time: '20:00',
      source: 'municipal_api',
    });

    expect(schedule.id).toBe(seeded.id);
    expect(getLocalHouseLedger().garbageSchedules).toHaveLength(1);
    expect(schedule.municipality).toBe('Burnaby');
    expect(schedule.set_out_time).toBe('20:00');
    expect(schedule.source).toBe('municipal_api');
  });

  it('updateSchedule leaves untouched fields alone', async () => {
    const ledger = await freshSession();
    const { schedule: created } = await localGarbageApi.createSchedule(ledger.household.id, {
      municipality: 'Surrey',
      schedules: [weekly('garbage', 3)],
      set_out_time: '18:30',
    });

    const { schedule } = await localGarbageApi.updateSchedule(ledger.household.id, created.id, {
      schedules: [weekly('garbage', 4), weekly('recycling', 4)],
    });

    expect(schedule.municipality).toBe('Surrey');
    expect(schedule.set_out_time).toBe('18:30');
    expect(schedule.schedules).toHaveLength(2);
    expect(schedule.updated_at >= created.updated_at).toBe(true);
  });

  it('expands the stored row into dates through getNextCollections', async () => {
    const ledger = await freshSession();
    const { schedule } = await localGarbageApi.createSchedule(ledger.household.id, {
      municipality: 'Vancouver',
      schedules: [weekly('garbage', 3)],
    });

    const { dates } = await localGarbageApi.getNextCollections(
      ledger.household.id,
      schedule.id,
      14,
    );
    // Relative to "now", so assert the shape and the cadence rather than a date.
    expect(dates.length).toBeGreaterThan(0);
    expect(dates.length).toBeLessThanOrEqual(3);
    for (const entry of dates) {
      expect(entry.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(entry.types).toEqual(['garbage']);
    }
  });

  it('refuses to expand a schedule this property does not own', async () => {
    const ledger = await freshSession();
    await localGarbageApi.getSchedule(ledger.household.id);
    await expect(
      localGarbageApi.getNextCollections(ledger.household.id, 'gsch_nope', 14),
    ).rejects.toThrow('Garbage schedule not found');
  });

  it('splits a flat reminder list into presets plus custom, keeping absent presets', async () => {
    const ledger = await freshSession();
    const { schedule: created } = await localGarbageApi.createSchedule(ledger.household.id, {
      municipality: 'Vancouver',
      schedules: [weekly('garbage', 3)],
    });

    const { schedule } = await localGarbageApi.updateReminders(ledger.household.id, created.id, [
      { id: 'r1', type: 'evening_before', time: '20:30', daysOffset: -1, label: 'Evening Before', enabled: true },
      { id: 'r2', type: 'custom', time: '17:00', daysOffset: -2, label: '2 Days Prior', enabled: true },
    ]);

    expect(schedule.reminders?.nightBefore).toEqual({ enabled: true, time: '20:30' });
    // No `morning_of` was sent, so the row keeps what it had.
    expect(schedule.reminders?.morningOf).toEqual({ enabled: false, time: '07:00' });
    expect(schedule.reminders?.custom).toHaveLength(1);

    // An empty custom list is stored as undefined, not [] — server parity.
    const cleared = await localGarbageApi.updateReminders(ledger.household.id, created.id, [
      { id: 'r3', type: 'morning_of', time: '06:45', daysOffset: 0, label: 'Morning Of', enabled: true },
    ]);
    expect(cleared.schedule.reminders?.custom).toBeUndefined();
    expect(cleared.schedule.reminders?.morningOf).toEqual({ enabled: true, time: '06:45' });
    expect(cleared.schedule.reminders?.nightBefore).toEqual({ enabled: true, time: '20:30' });
  });
});

describe('localGarbageApi — tier boundaries are declared, not implied', () => {
  afterEach(async () => {
    await resetLocalHouseSession();
  });

  it('leaves the three Tier-C municipality reads to the server', () => {
    expect([...HOUSE_LOCAL_GARBAGE_REMOTE_METHODS]).toEqual([
      'getMunicipalities',
      'getMunicipality',
      'getWasteRegulations',
    ]);
    // Declared remote means genuinely NOT implemented here: if one of these
    // grew a local stub the Proxy would still route it remotely, and the two
    // would silently disagree.
    for (const name of HOUSE_LOCAL_GARBAGE_REMOTE_METHODS) {
      expect(name in localGarbageApi).toBe(false);
    }
  });

  it('throws member-facing copy for aiDetect (H7), never a silent server call', async () => {
    await freshSession();
    await expect(localGarbageApi.aiDetect()).rejects.toBeInstanceOf(HouseLocalUnsupportedError);
    const error = await localGarbageApi.aiDetect().catch((e) => e);
    expect(error.message).toBe(getHouseUnsupportedCopy('garbage-collection.aiDetect').message);
    expect(error.message).not.toContain('garbage-collection.aiDetect');
  });

  it('implements every remote method that is not declared remote-by-design', () => {
    const remoteMethods = [
      'getSchedule',
      'createSchedule',
      'updateSchedule',
      'getNextCollections',
      'aiDetect',
      'getMunicipalities',
      'getMunicipality',
      'getWasteRegulations',
      'updateReminders',
    ];
    const declaredRemote = new Set<string>(HOUSE_LOCAL_GARBAGE_REMOTE_METHODS);
    const expectedLocal = remoteMethods.filter((name) => !declaredRemote.has(name));

    expect(Object.keys(localGarbageApi).sort()).toEqual([...expectedLocal].sort());
  });
});
