/**
 * HealthStatTiles + HealthGoalBar — the summary primitives shared by the Health
 * section tabs (Nutrition / Activity / Trends / Body).
 *
 * The section-screen suite renders these only through real screens, which
 * exercises one shape each: every tile with an icon, every bar with an explicit
 * colour and a positive target. This suite drives them DIRECTLY so the optional
 * props and the defensive arithmetic are covered too — the branches that only
 * appear when a caller omits an icon, omits a tint, or hands over a zero target
 * (an unset goal), where `value / target` would otherwise be Infinity or NaN and
 * the bar would render an invalid width.
 */

 
import React from 'react';
import { StyleSheet } from 'react-native';
import ReactTestRenderer, { act } from 'react-test-renderer';

import { Icon } from '@components/ui/Icon';
import { ThemeProvider } from '@contexts/ThemeContext';

import { HealthGoalBar, HealthStatTiles, type HealthStat } from '../HealthStatTiles';

type Rendered = ReactTestRenderer.ReactTestRenderer;

function render(element: React.ReactElement): Rendered {
  let tree!: Rendered;
  act(() => {
    tree = ReactTestRenderer.create(<ThemeProvider>{element}</ThemeProvider>);
  });
  return tree;
}

function byTestId(tree: Rendered, id: string) {
  return tree.root.findAll((n) => typeof n.type === 'string' && n.props?.testID === id);
}

/** Concatenated text of a host subtree. */
function textOf(inst: ReactTestRenderer.ReactTestInstance): string {
  return inst
    .findAll((n) => typeof n.type === 'string')
    .flatMap((n) => {
      const c = n.props?.children;
      return Array.isArray(c) ? c : [c];
    })
    .filter((c) => typeof c === 'string' || typeof c === 'number')
    .map(String)
    .join('');
}

/**
 * Every `<Icon>` the tree rendered, in tree order.
 *
 * Matched on the Icon COMPONENT, not structurally on "any node carrying `name`
 * and `size`". The shared primitive resolves a name against the active brand's
 * PNG kit (`src/brand/icons.generated.ts` — GENERATED, and regenerated by
 * `icons:build` for whichever APP_BRAND is being built) and only falls through
 * to `<Ionicons>` when that kit has no such slug. The PNG branch renders one
 * matching node; the Ionicons branch renders a chain of them, each re-forwarding
 * `name` and `size`. So the structural match returned 1 or 3 entries for the
 * same single glyph depending purely on which brand's kit happened to be
 * checked in — `nutrition` and `workouts` exist in `brands/symply-health` but
 * not in `brands/symply-house`, which is what Jest pins. Matching the component
 * counts glyphs, which is what every assertion below is actually about.
 */
function iconNames(tree: Rendered): string[] {
  return tree.root.findAll((n) => n.type === Icon).map((n) => n.props.name as string);
}

/** The goal bar's fill node — styles arrive as an array, so flatten first. */
function fillNode(tree: Rendered, testID: string) {
  const bar = byTestId(tree, testID)[0];
  return bar.findAll((n) => {
    if (typeof n.type !== 'string') return false;
    const flat = StyleSheet.flatten(n.props?.style) as { width?: unknown } | undefined;
    return typeof flat?.width === 'string' && flat.width.endsWith('%');
  })[0];
}

function fillWidth(tree: Rendered, testID: string): string | undefined {
  const flat = StyleSheet.flatten(fillNode(tree, testID)?.props?.style) as
    | { width?: string }
    | undefined;
  return flat?.width;
}

function fillColor(tree: Rendered, testID: string): string | undefined {
  const flat = StyleSheet.flatten(fillNode(tree, testID)?.props?.style) as
    | { backgroundColor?: string }
    | undefined;
  return flat?.backgroundColor;
}

describe('HealthStatTiles', () => {
  const stats: HealthStat[] = [
    { label: 'Calories', value: '1,850', icon: 'nutrition', testID: 'stat-calories' },
    { label: 'Protein', value: '96 g', testID: 'stat-protein' },
  ];

  it('HEALTH-TILE-001: renders one tile per stat, keyed by label', () => {
    const tree = render(<HealthStatTiles stats={stats} />);
    expect(byTestId(tree, 'stat-calories')).toHaveLength(1);
    expect(byTestId(tree, 'stat-protein')).toHaveLength(1);
  });

  it('HEALTH-TILE-002: merges each tile into one labelled element for assistive tech', () => {
    const tree = render(<HealthStatTiles stats={stats} />);
    const tile = byTestId(tree, 'stat-calories')[0];
    expect(tile.props.accessible).toBe(true);
    // "Calories: 1,850" — label and value read as one phrase, not two nodes.
    expect(tile.props.accessibilityLabel).toBe('Calories: 1,850');
    expect(textOf(tile)).toContain('1,850');
  });

  it('HEALTH-TILE-003: renders the glyph only for stats that declare one', () => {
    const tree = render(<HealthStatTiles stats={stats} />);
    // Calories declares `nutrition`; Protein declares no icon and must render none.
    expect(iconNames(tree)).toEqual(['nutrition']);
    expect(textOf(byTestId(tree, 'stat-protein')[0])).toContain('96 g');
  });

  it('HEALTH-TILE-004: renders nothing for an empty stat list', () => {
    const tree = render(<HealthStatTiles stats={[]} />);
    expect(iconNames(tree)).toEqual([]);
    expect(tree.root.findAll((n) => n.props?.accessibilityLabel != null)).toHaveLength(0);
  });

  it('HEALTH-TILE-005: a tile without a testID still renders and stays labelled', () => {
    const tree = render(<HealthStatTiles stats={[{ label: 'Steps', value: '8,240' }]} />);
    const labelled = tree.root.findAll((n) => n.props?.accessibilityLabel === 'Steps: 8,240');
    expect(labelled.length).toBeGreaterThan(0);
    expect(labelled[0].props.testID).toBeUndefined();
  });

  it('HEALTH-TILE-016: a `color` tints a badge behind the glyph instead of the plain layout', () => {
    const tree = render(
      <HealthStatTiles
        stats={[
          { label: 'Workouts', value: '4', icon: 'workouts', color: '#34C759', testID: 'stat-tinted' },
        ]}
      />,
    );
    const tile = byTestId(tree, 'stat-tinted')[0];
    const icon = tile.findAll((n) => n.props?.name === 'workouts')[0];
    expect(icon.props.color).toBe('#34C759');
    expect(textOf(tile)).toContain('4');
    expect(textOf(tile)).toContain('Workouts');
  });

  it('HEALTH-TILE-017: omitting `color` keeps the existing plain layout (icon tinted secondary)', () => {
    const tree = render(<HealthStatTiles stats={stats} />);
    const icon = byTestId(tree, 'stat-calories')[0].findAll((n) => n.props?.name === 'nutrition')[0];
    // The plain layout's glyph is a small secondary-text icon, never the
    // stat's own colour — that only happens once a caller opts in via `color`.
    expect(icon.props.color).not.toBe('#34C759');
  });
});

describe('HealthGoalBar', () => {
  it('HEALTH-TILE-006: reads out "x of y" with the unit suffix', () => {
    const tree = render(
      <HealthGoalBar label="Protein" value={96} target={140} suffix="g" testID="goal-protein" />,
    );
    const bar = byTestId(tree, 'goal-protein')[0];
    expect(bar.props.accessible).toBe(true);
    expect(bar.props.accessibilityLabel).toBe('Protein: 96 of 140g');
    // Grams + share of the goal — matches the donor's own `macroProgressBar`
    // ("\(Int(value))g (\(percentage)%)"), not a bare `value / target`.
    expect(textOf(bar)).toContain('96g (69%)');
  });

  it('HEALTH-TILE-007: omits the suffix when the caller gives none', () => {
    const tree = render(<HealthGoalBar label="Steps" value={8240} target={10000} testID="goal-steps" />);
    expect(byTestId(tree, 'goal-steps')[0].props.accessibilityLabel).toBe('Steps: 8240 of 10000');
  });

  it('HEALTH-TILE-008: rounds fractional values in both the label and the readout', () => {
    const tree = render(
      <HealthGoalBar label="Carbs" value={96.4} target={139.6} suffix="g" testID="goal-carbs" />,
    );
    const bar = byTestId(tree, 'goal-carbs')[0];
    expect(bar.props.accessibilityLabel).toBe('Carbs: 96 of 140g');
    expect(textOf(bar)).toContain('96g (69%)');
  });

  it('HEALTH-TILE-016: omits the percentage when there is no real target to be a share of', () => {
    const tree = render(<HealthGoalBar label="Fibre" value={12} target={0} testID="goal-zero-pct" />);
    const bar = byTestId(tree, 'goal-zero-pct')[0];
    expect(textOf(bar)).toBe('Fibre12');
    expect(textOf(bar)).not.toContain('%');
  });

  it('HEALTH-TILE-009: fills proportionally', () => {
    const tree = render(<HealthGoalBar label="Protein" value={70} target={140} testID="goal-half" />);
    expect(fillWidth(tree, 'goal-half')).toBe('50%');
  });

  it('HEALTH-TILE-010: clamps an overshoot to a full bar rather than overflowing', () => {
    const tree = render(<HealthGoalBar label="Protein" value={200} target={140} testID="goal-over" />);
    expect(fillWidth(tree, 'goal-over')).toBe('100%');
  });

  it('HEALTH-TILE-011: clamps a negative value to an empty bar', () => {
    const tree = render(<HealthGoalBar label="Deficit" value={-50} target={140} testID="goal-neg" />);
    expect(fillWidth(tree, 'goal-neg')).toBe('0%');
  });

  it('HEALTH-TILE-012: an unset (zero) target cannot divide by zero', () => {
    // `value / 0` is Infinity, which would render `width: Infinity%`. The guard
    // substitutes 1, so any positive value simply reads as a full bar.
    const tree = render(<HealthGoalBar label="Fibre" value={12} target={0} testID="goal-zero" />);
    expect(fillWidth(tree, 'goal-zero')).toBe('100%');
    expect(byTestId(tree, 'goal-zero')[0].props.accessibilityLabel).toBe('Fibre: 12 of 0');
  });

  it('HEALTH-TILE-013: a negative target is treated the same as an unset one', () => {
    const tree = render(<HealthGoalBar label="Fibre" value={0} target={-10} testID="goal-negtarget" />);
    expect(fillWidth(tree, 'goal-negtarget')).toBe('0%');
  });

  it('HEALTH-TILE-014: honours an explicit tint and falls back to the brand primary', () => {
    const tinted = render(
      <HealthGoalBar label="Fat" value={40} target={60} color="#123456" testID="goal-tinted" />,
    );
    expect(fillColor(tinted, 'goal-tinted')).toBe('#123456');

    // Falls back to the theme primary rather than rendering an undefined colour.
    const plain = render(<HealthGoalBar label="Fat" value={40} target={60} testID="goal-plain" />);
    expect(fillColor(plain, 'goal-plain')).toBeTruthy();
    expect(fillColor(plain, 'goal-plain')).not.toBe('#123456');
  });

  it('HEALTH-TILE-015: renders without a testID', () => {
    const tree = render(<HealthGoalBar label="Water" value={4} target={8} />);
    const labelled = tree.root.findAll((n) => n.props?.accessibilityLabel === 'Water: 4 of 8');
    expect(labelled.length).toBeGreaterThan(0);
    expect(labelled[0].props.testID).toBeUndefined();
  });
});
