/**
 * HealthScaleRow + HealthToggleRow — the two self-report controls shared by the
 * Cycle and Vitality tabs (libido, energy, mood, stress, sleep, flow, severity,
 * and the yes/no rows beside them).
 *
 * Both screens render them, so the primary path is already exercised there.
 * This suite drives them DIRECTLY for the parts a screen cannot reach: the
 * optional props (the toggle's leading glyph, the caption under a scale), and
 * the one distinction the whole control exists to keep — an UNRATED day reads
 * as unrated, never as a zero the member did not choose.
 */

import React from 'react';
import ReactTestRenderer, { act } from 'react-test-renderer';

import { Icon } from '@components/ui/Icon';
import { ThemeProvider } from '@contexts/ThemeContext';

import { HealthScaleRow, HealthToggleRow } from '../HealthScaleRow';

type Rendered = ReactTestRenderer.ReactTestRenderer;

function render(element: React.ReactElement): Rendered {
  let tree!: Rendered;
  act(() => {
    tree = ReactTestRenderer.create(<ThemeProvider>{element}</ThemeProvider>);
  });
  return tree;
}

function byTestId(tree: Rendered, id: string) {
  return tree.root.findAll((n) => typeof n.type === 'string' && n.props?.testID === id);
}

/** Concatenated text of a host subtree. */
function textOf(tree: Rendered): string {
  const out: string[] = [];
  const walk = (node: ReactTestRenderer.ReactTestInstance | string) => {
    if (typeof node === 'string') {
      out.push(node);
      return;
    }
    for (const child of node.children) walk(child as never);
  };
  walk(tree.root);
  return out.join(' ');
}

/**
 * Every `<Icon>` the tree rendered, in tree order.
 *
 * Matched on the Icon COMPONENT, not structurally on "any node carrying `name`
 * and `size`". The shared primitive resolves a name against the active brand's
 * PNG kit (`src/brand/icons.generated.ts` — GENERATED, and regenerated by
 * `icons:build` for whichever APP_BRAND is being built) and only falls through
 * to `<Ionicons>` when that kit has no such slug. The PNG branch renders one
 * matching node; the Ionicons branch renders a chain of them, each re-forwarding
 * `name` and `size`. So the structural match returned 1 or 3 entries for the
 * same single glyph depending purely on which brand's kit happened to be
 * checked in — `workouts` and `nutrition` exist in `brands/symply-health` but
 * not in `brands/symply-house`, which is what Jest pins. Matching the component
 * counts glyphs, which is what every assertion below is actually about.
 */
function iconNames(tree: Rendered): string[] {
  return tree.root.findAll((n) => n.type === Icon).map((n) => n.props.name as string);
}

/** Fire onPress on the composite carrying `testID`, not on its host View. */
function press(tree: Rendered, testID: string) {
  const node = tree.root.find(
    (n) => n.props?.testID === testID && typeof n.props?.onPress === 'function'
  );
  act(() => node.props.onPress());
}

describe('HealthScaleRow', () => {
  it('HEALTH-SCALE-001: an unrated day reads as unrated, never as a zero', () => {
    const tree = render(
      <HealthScaleRow label="Energy" value={null} onChange={jest.fn()} testID="scale-energy" />
    );

    // "0/10" would be a rating the member never gave, and the Cycle/Vitality
    // stores treat null and 0 as different facts.
    expect(textOf(tree)).toContain('—');
    expect(textOf(tree)).not.toContain('0/10');
    expect(
      byTestId(tree, 'scale-energy-1')[0].props.accessibilityState.selected
    ).toBe(false);
  });

  it('HEALTH-SCALE-002: reports the step that was tapped, and fills up to the value', () => {
    const onChange = jest.fn();
    const tree = render(
      <HealthScaleRow label="Energy" value={3} onChange={onChange} max={5} testID="scale-energy" />
    );

    expect(textOf(tree)).toContain('3/5');
    // Discrete segments, so the value announced is the value stored — no
    // slider rounding between what was touched and what is saved.
    expect(byTestId(tree, 'scale-energy-4')[0].props.accessibilityLabel).toBe('Energy: 4 of 5');
    press(tree, 'scale-energy-4');
    expect(onChange).toHaveBeenCalledWith(4);
    expect(byTestId(tree, 'scale-energy-6').length).toBe(0);
  });

  it('HEALTH-SCALE-003: the optional glyph and caption appear only when supplied', () => {
    const bare = render(
      <HealthScaleRow label="Libido" value={7} onChange={jest.fn()} testID="scale-libido" />
    );
    expect(iconNames(bare)).toEqual([]);
    expect(textOf(bare)).not.toContain('High drive');

    const dressed = render(
      <HealthScaleRow
        label="Libido"
        value={7}
        onChange={jest.fn()}
        icon="vitality"
        hint="High drive"
        testID="scale-libido"
      />
    );
    expect(iconNames(dressed)).toContain('vitality');
    expect(textOf(dressed)).toContain('High drive');
  });
});

describe('HealthToggleRow', () => {
  it('HEALTH-SCALE-004: announces its checked state and flips it on press', () => {
    const onChange = jest.fn();
    const tree = render(
      <HealthToggleRow label="Exercised" value={false} onChange={onChange} testID="toggle-ex" />
    );

    const row = tree.root.find(
      (n) => n.props?.testID === 'toggle-ex' && typeof n.props?.onPress === 'function'
    );
    expect(row.props.accessibilityRole).toBe('checkbox');
    expect(row.props.accessibilityState.checked).toBe(false);
    press(tree, 'toggle-ex');
    expect(onChange).toHaveBeenCalledWith(true);
  });

  it('HEALTH-SCALE-005: a leading glyph is optional, and only the tick is state-bound', () => {
    // The toggle sits in the same list as the scales above it, so it takes the
    // same optional glyph. What it must NOT do is draw the checkmark when it is
    // off — that tick is the only thing carrying the answer visually.
    const off = render(
      <HealthToggleRow
        label="Exercised"
        value={false}
        onChange={jest.fn()}
        icon="workouts"
        testID="toggle-ex"
      />
    );
    expect(iconNames(off)).toEqual(['workouts']);

    const on = render(
      <HealthToggleRow
        label="Exercised"
        value
        onChange={jest.fn()}
        icon="workouts"
        testID="toggle-ex"
      />
    );
    expect(iconNames(on)).toEqual(['checkmark', 'workouts']);

    const plain = render(
      <HealthToggleRow label="Exercised" value onChange={jest.fn()} testID="toggle-ex" />
    );
    expect(iconNames(plain)).toEqual(['checkmark']);
  });
});
