// GENERATED by scripts/build-tokens.mjs (APP_BRAND=symply-budget) — DO NOT EDIT.
// Sources: brands/_shared/tokens.base.json + brands/symply-budget/tokens.json
// Run: APP_BRAND=symply-budget npm run design:build
// BrandTokens — colors/gradients for Widget + Watch (add to Xcode target when wiring).

import SwiftUI

extension Color {
  init(hex: UInt32) {
    self.init(
      .sRGB,
      red: Double((hex >> 16) & 0xFF) / 255,
      green: Double((hex >> 8) & 0xFF) / 255,
      blue: Double(hex & 0xFF) / 255,
      opacity: 1
    )
  }
}

enum BrandTokens {
  // Brand identity — used by the shared Symply Widget/Watch kit to read this brand's
  // App Group data and pick per-app content. Regenerated per APP_BRAND at build.
  static let brandId = "symply-budget"
  static let appKey = "budget"
  static let appGroup = "group.com.symply.budget"

  static let primary = Color(hex: 0x2BB673)
  static let primaryDark = Color(hex: 0x239A61)
  static let primaryLight = Color(hex: 0x5FD49A)
  static let primaryOnDark = Color(hex: 0x239A61)
  static let primaryDarkOnDark = Color(hex: 0x1B7A4C)
  static let white = Color(hex: 0xFFFFFF)
  static let ink = Color(hex: 0x0A1325)

  static var mint: Color { primary }
  static var mintDark: Color { primaryDark }

  static let brandGradient = LinearGradient(
    gradient: Gradient(stops: [
      .init(color: Color(hex: 0x2BB673), location: 0),
      .init(color: Color(hex: 0x239A61), location: 0.5),
      .init(color: Color(hex: 0x1B7A4C), location: 1)
    ]),
    startPoint: UnitPoint(x: 0, y: 0),
    endPoint: UnitPoint(x: 1, y: 1)
  )

  static func background(_ scheme: ColorScheme) -> LinearGradient {
    scheme == .dark
      ? LinearGradient(
    gradient: Gradient(stops: [
      .init(color: Color(hex: 0x0A1325), location: 0),
      .init(color: Color(hex: 0x122033), location: 0.55),
      .init(color: Color(hex: 0x1A2A3A), location: 1)
    ]),
    startPoint: UnitPoint(x: 0.05, y: 0),
    endPoint: UnitPoint(x: 0.95, y: 1)
  )
      : LinearGradient(
    gradient: Gradient(stops: [
      .init(color: Color(hex: 0xFFFFFF), location: 0),
      .init(color: Color(hex: 0xEAF8F1), location: 0.4),
      .init(color: Color(hex: 0xD9F2E6), location: 1)
    ]),
    startPoint: UnitPoint(x: 0.5, y: 0),
    endPoint: UnitPoint(x: 0.5, y: 1)
  )
  }

  static func primaryText(_ scheme: ColorScheme) -> Color {
    scheme == .dark ? Color(hex: 0xF7FAFF) : Color(hex: 0x0A1325)
  }

  static let fontDesign: Font.Design = .default
  static func font(_ size: CGFloat, _ weight: Font.Weight = .regular) -> Font {
    .system(size: size, weight: weight, design: fontDesign)
  }
}
