//
//  WidgetTheme.swift
//  SymplyEcosystemWidget
//
//  Brand colors, tone → accent mapping, and an Ionicons → SF Symbol bridge so
//  the widget can render the backend's icon names (which are Ionicons) natively.
//  Mint accents come from BrandTokens (generated by `npm run design:build`).
//

import SwiftUI

enum WidgetTheme {
    // Brand palette — primary from DesignTokens.generated.swift
    static var mint: Color { BrandTokens.primary }
    static var mintDark: Color { BrandTokens.primaryDark }
    static let urgentRed = Color(red: 1.0, green: 0.231, blue: 0.188)  // #FF3B30
    static let amber = Color(red: 1.0, green: 0.624, blue: 0.039)      // #FF9F0A
    static let green = Color(red: 0.204, green: 0.780, blue: 0.349)    // #34C759

    /// Accent + soft wash for a given insight tone. Mirrors `HomeMiraBrief`.
    static func colors(for tone: String) -> (accent: Color, wash: Color) {
        switch tone {
        case "urgent":
            return (urgentRed, urgentRed.opacity(0.12))
        case "attention":
            return (amber, amber.opacity(0.14))
        case "celebrate":
            return (green, green.opacity(0.14))
        case "info", "calm":
            return (mint, mint.opacity(0.12))
        default:
            return (mint, mint.opacity(0.12))
        }
    }
}

// MARK: - Shared layout kit (same conventions across every app's widget + watch)
//
// Per-app widgets differ in CONTENT (tasks vs budget vs habits vs lessons vs health)
// but MUST share these layout primitives so they look like one product line. Build
// every widget/watch view from `SymplyCard`, `SymplyHeader`, `SymplyStatTile`,
// `SymplyListRow`, `SymplyEmptyState` — never ad-hoc paddings/corners.

/// Spacing / radius / type scale — the single source of layout truth.
enum SymplyLayout {
    static let gutter: CGFloat = 12       // outer padding
    static let gap: CGFloat = 8           // between elements
    static let tightGap: CGFloat = 4
    static let corner: CGFloat = 16
    static let tileCorner: CGFloat = 12
    static let iconChip: CGFloat = 22
}

/// Standard card container — brand background + rounded corners. Wrap every widget
/// body in this so all apps share the same surface treatment.
struct SymplyCard<Content: View>: View {
    @Environment(\.colorScheme) private var scheme
    let content: Content
    init(@ViewBuilder _ content: () -> Content) { self.content = content() }
    var body: some View {
        content
            .padding(SymplyLayout.gutter)
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
            .background(BrandTokens.background(scheme))
    }
}

/// Header row: brand-tinted icon chip + title (+ optional trailing value). Every
/// widget/watch screen leads with this for a consistent identity.
struct SymplyHeader: View {
    @Environment(\.colorScheme) private var scheme
    let icon: String          // SF Symbol — used when `logoImageName` is nil
    let title: String
    var trailing: String? = nil
    var tint: Color = BrandTokens.primary
    /// Optional named asset (app icon / wordmark) rendered instead of the SF
    /// Symbol chip — lets a brand show its real logo instead of a generic glyph.
    var logoImageName: String? = nil
    var body: some View {
        HStack(spacing: SymplyLayout.gap) {
            if let logoImageName {
                Image(logoImageName)
                    .resizable()
                    .aspectRatio(contentMode: .fill)
                    .frame(width: SymplyLayout.iconChip, height: SymplyLayout.iconChip)
                    .clipShape(RoundedRectangle(cornerRadius: 7, style: .continuous))
            } else {
                Image(systemName: icon)
                    .font(.system(size: 12, weight: .bold))
                    .foregroundStyle(.white)
                    .frame(width: SymplyLayout.iconChip, height: SymplyLayout.iconChip)
                    .background(tint, in: RoundedRectangle(cornerRadius: 7, style: .continuous))
            }
            Text(title)
                .font(BrandTokens.font(13, .semibold))
                .foregroundStyle(BrandTokens.primaryText(scheme))
                .lineLimit(1)
            if let trailing {
                Spacer(minLength: SymplyLayout.tightGap)
                Text(trailing)
                    .font(BrandTokens.font(13, .bold))
                    .foregroundStyle(tint)
                    .lineLimit(1)
            }
        }
    }
}

/// A single metric tile (big value + caption). Used for stat rows on every app.
struct SymplyStatTile: View {
    @Environment(\.colorScheme) private var scheme
    let value: String
    let caption: String
    var tint: Color = BrandTokens.primary
    var body: some View {
        VStack(alignment: .leading, spacing: SymplyLayout.tightGap) {
            Text(value)
                .font(BrandTokens.font(20, .bold))
                .foregroundStyle(tint)
                .lineLimit(1)
                .minimumScaleFactor(0.6)
            Text(caption)
                .font(BrandTokens.font(10, .medium))
                .foregroundStyle(BrandTokens.primaryText(scheme).opacity(0.6))
                .lineLimit(1)
        }
        .padding(SymplyLayout.gap)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(tint.opacity(0.10), in: RoundedRectangle(cornerRadius: SymplyLayout.tileCorner, style: .continuous))
    }
}

/// Slim rounded progress track (spend-vs-budget, goal completion, …). `progress`
/// is unclamped input but the fill is visually clamped to 100% — an over-budget
/// month reads as a full bar, never an overflowing one.
struct SymplyProgressBar: View {
    @Environment(\.colorScheme) private var scheme
    let progress: Double
    var tint: Color = BrandTokens.primary
    var height: CGFloat = 6
    var body: some View {
        GeometryReader { geo in
            ZStack(alignment: .leading) {
                Capsule()
                    .fill(BrandTokens.primaryText(scheme).opacity(0.08))
                Capsule()
                    .fill(tint)
                    .frame(width: geo.size.width * min(max(progress, 0), 1))
            }
        }
        .frame(height: height)
    }
}

/// A compact AI-generated message row (insight / encouragement / reminder) — a
/// tone-tinted emoji badge + message text. All copy is server-composed; the
/// widget only renders it, same convention as `HomeInsightData`.
struct SymplyInsightBanner: View {
    @Environment(\.colorScheme) private var scheme
    let emoji: String?
    let message: String
    var tint: Color = BrandTokens.primary
    var lineLimit: Int = 2
    var body: some View {
        HStack(alignment: .top, spacing: SymplyLayout.gap) {
            Text((emoji?.isEmpty == false) ? emoji! : "✨")
                .font(.system(size: 12))
                .frame(width: SymplyLayout.iconChip, height: SymplyLayout.iconChip)
                .background(tint.opacity(0.18), in: RoundedRectangle(cornerRadius: 7, style: .continuous))
            Text(message)
                .font(BrandTokens.font(11, .medium))
                .foregroundStyle(BrandTokens.primaryText(scheme).opacity(0.85))
                .lineLimit(lineLimit)
                .fixedSize(horizontal: false, vertical: true)
            Spacer(minLength: 0)
        }
        .padding(SymplyLayout.tightGap)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(tint.opacity(0.08), in: RoundedRectangle(cornerRadius: SymplyLayout.tileCorner, style: .continuous))
    }
}

/// A list row (icon + primary text + optional secondary). Task feeds, habit lists,
/// lesson lists, etc. all render as these so the rhythm is identical.
struct SymplyListRow: View {
    @Environment(\.colorScheme) private var scheme
    let icon: String
    let text: String
    var detail: String? = nil
    var tint: Color = BrandTokens.primary
    var body: some View {
        HStack(spacing: SymplyLayout.gap) {
            Image(systemName: icon)
                .font(.system(size: 11, weight: .semibold))
                .foregroundStyle(tint)
                .frame(width: 16)
            Text(text)
                .font(BrandTokens.font(12, .medium))
                .foregroundStyle(BrandTokens.primaryText(scheme))
                .lineLimit(1)
            if let detail {
                Spacer(minLength: SymplyLayout.tightGap)
                Text(detail)
                    .font(BrandTokens.font(11, .regular))
                    .foregroundStyle(BrandTokens.primaryText(scheme).opacity(0.55))
                    .lineLimit(1)
            }
        }
    }
}

/// Empty / signed-out state — same look everywhere.
struct SymplyEmptyState: View {
    @Environment(\.colorScheme) private var scheme
    let icon: String
    let message: String
    var body: some View {
        VStack(spacing: SymplyLayout.gap) {
            Image(systemName: icon)
                .font(.system(size: 22, weight: .light))
                .foregroundStyle(BrandTokens.primary.opacity(0.7))
            Text(message)
                .font(BrandTokens.font(12, .medium))
                .foregroundStyle(BrandTokens.primaryText(scheme).opacity(0.6))
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

/// Maps an Ionicons name (from the backend) to the closest SF Symbol.
enum Ionicon {
    static func symbol(_ name: String?) -> String {
        guard let name else { return "sparkles" }
        switch name {
        // status
        case "alert-circle", "alert-circle-outline", "warning", "warning-outline":
            return "exclamationmark.circle.fill"
        case "checkmark-circle", "checkmark-circle-outline", "checkmark-done":
            return "checkmark.circle.fill"
        case "checkmark":
            return "checkmark"
        case "sparkles":
            return "sparkles"
        // tasks / time
        case "calendar", "calendar-outline", "today", "today-outline":
            return "calendar"
        case "time", "time-outline", "alarm", "alarm-outline":
            return "clock.fill"
        case "list", "list-outline", "checkbox", "checkbox-outline":
            return "checklist"
        case "flag", "flag-outline":
            return "flag.fill"
        // money
        case "card", "card-outline":
            return "creditcard.fill"
        case "wallet", "wallet-outline", "cash", "cash-outline", "pricetag", "pricetag-outline":
            return "wallet.pass.fill"
        case "trending-up", "trending-up-outline":
            return "chart.line.uptrend.xyaxis"
        case "receipt", "receipt-outline":
            return "doc.text.fill"
        // home / property
        case "home", "home-outline":
            return "house.fill"
        case "business", "business-outline":
            return "building.2.fill"
        case "document-text", "document-text-outline", "document", "document-outline":
            return "doc.text.fill"
        // utilities
        case "flash", "flash-outline":
            return "bolt.fill"
        case "water", "water-outline":
            return "drop.fill"
        case "flame", "flame-outline":
            return "flame.fill"
        case "trash", "trash-outline":
            return "trash.fill"
        case "leaf", "leaf-outline":
            return "leaf.fill"
        case "wifi":
            return "wifi"
        // Kaizen systems — emitted by the phone's widget/watch snapshot producer
        // (SYSTEM_ICON in src/features/kaizen/services/kaizenWidgetSnapshot.ts).
        // Without these the next-habit glyph silently degrades to "sparkles".
        case "briefcase", "briefcase-outline":
            return "briefcase.fill"
        case "book", "book-outline":
            return "book.fill"
        case "help-circle", "help-circle-outline":
            return "questionmark.circle.fill"
        case "fitness", "fitness-outline":
            return "figure.run"
        case "timer", "timer-outline":
            return "timer"
        // misc
        case "construct", "construct-outline", "build", "build-outline", "hammer":
            return "wrench.and.screwdriver.fill"
        case "bulb", "bulb-outline":
            return "lightbulb.fill"
        case "notifications", "notifications-outline":
            return "bell.fill"
        case "chevron-forward":
            return "chevron.right"
        default:
            return "sparkles"
        }
    }
}
