#!/usr/bin/env node
/**
 * Generate RN + Swift design tokens from brand packs.
 *   APP_BRAND=symply-house npm run tokens:build
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const brandId = (
  process.env.EXPO_PUBLIC_APP_BRAND ||
  process.env.APP_BRAND ||
  'simple-house'
).trim();

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function unwrap(node) {
  if (node == null || typeof node !== 'object' || Array.isArray(node)) {
    return node;
  }
  if (Object.prototype.hasOwnProperty.call(node, '$value')) {
    return node.$value;
  }
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$') || k.startsWith('_')) continue;
    out[k] = unwrap(v);
  }
  return out;
}

function flattenTypography(typo) {
  const out = {};
  for (const [name, spec] of Object.entries(typo || {})) {
    if (!spec || typeof spec !== 'object') continue;
    out[name] = {
      size: spec.size?.$value ?? spec.size,
      weight: spec.weight?.$value ?? spec.weight,
      lineHeight: spec.lineHeight?.$value ?? spec.lineHeight,
      ...(spec.letterSpacing != null
        ? { letterSpacing: spec.letterSpacing?.$value ?? spec.letterSpacing }
        : {}),
    };
  }
  return out;
}

function hex(h) {
  return `0x${String(h).replace('#', '').toUpperCase()}`;
}

function rgbaToSwift(s) {
  const m = String(s).match(/rgba?\(([^)]+)\)/);
  if (!m) return `Color(hex: ${hex(s)})`;
  const [r, g, b, a = '1'] = m[1].split(',').map(n => n.trim());
  const f = n => (Number(n) / 255).toFixed(4);
  return `Color(.sRGB, red: ${f(r)}, green: ${f(g)}, blue: ${f(b)}, opacity: ${Number(a)})`;
}

function colorSwift(v) {
  return String(v).startsWith('rgb') ? rgbaToSwift(v) : `Color(hex: ${hex(v)})`;
}

function swiftGradient(spec) {
  const stops = spec.colors
    .map(
      (c, i) =>
        `      .init(color: Color(hex: ${hex(c)}), location: ${spec.locations[i]})`,
    )
    .join(',\n');
  return `LinearGradient(\n    gradient: Gradient(stops: [\n${stops}\n    ]),\n    startPoint: UnitPoint(x: ${spec.start.x}, y: ${spec.start.y}),\n    endPoint: UnitPoint(x: ${spec.end.x}, y: ${spec.end.y})\n  )`;
}

function main() {
  const sharedPath = path.join(REPO, 'brands/_shared/tokens.base.json');
  const brandPath = path.join(REPO, 'brands', brandId, 'tokens.json');
  if (!fs.existsSync(sharedPath)) {
    console.error(`Missing ${sharedPath}`);
    process.exit(1);
  }
  if (!fs.existsSync(brandPath)) {
    console.error(`Missing ${brandPath}`);
    process.exit(1);
  }

  const shared = readJson(sharedPath);
  const brandTok = readJson(brandPath);

  // Brand identity for the shared Widget/Watch kit: the per-brand App Group (so the
  // widget/watch read THIS brand's data, not a hardcoded one) and a stable app key
  // (house/budget/kaizen/language/health) used to switch per-app content.
  const brandPackPath = path.join(REPO, 'brands', brandId, 'brand.cjs');
  const brandPack = fs.existsSync(brandPackPath) ? require(brandPackPath) : {};
  const iosBundleId = brandPack.iosBundleId || 'com.symply.house';
  const appGroup = brandPack.ios?.appGroup || `group.${iosBundleId}`;
  const appKey = iosBundleId.replace(/^com\.symply\./, '');
  const brandColors = unwrap(brandTok.brand);
  const gradients = unwrap(brandTok.gradients);
  const modes = unwrap(brandTok.modes);
  const semantic = unwrap(brandTok.semantic);
  const spacing = unwrap(shared.spacing);
  const radii = unwrap(shared.radii);
  const typography = flattenTypography(shared.typography);
  const fontsRaw = shared.fonts || {};
  const fonts = {
    family: unwrap(fontsRaw.family),
    nativeDesign: fontsRaw.nativeDesign?.$value ?? fontsRaw.nativeDesign ?? 'default',
  };

  const header = from =>
    `// GENERATED by scripts/build-tokens.mjs (APP_BRAND=${brandId}) — DO NOT EDIT.\n` +
    `// Sources: brands/_shared/tokens.base.json + brands/${brandId}/tokens.json\n` +
    `// Run: APP_BRAND=${brandId} npm run design:build\n` +
    (from ? `// ${from}\n` : '');

  const brandTs =
    header('Brand colors, gradients, modes, semantic for the RN app.') +
    `\nexport const brandColors = ${JSON.stringify(brandColors, null, 2)} as const;\n\n` +
    `export const gradients = ${JSON.stringify(gradients, null, 2)} as const;\n\n` +
    `export const themeColors = ${JSON.stringify(modes, null, 2)} as const;\n\n` +
    `export const semantic = ${JSON.stringify(semantic, null, 2)} as const;\n`;

  const themeTs =
    header('Shared spacing, radii, typography, fonts.') +
    `\nexport const spacing = ${JSON.stringify(spacing, null, 2)} as const;\n\n` +
    `export const radii = ${JSON.stringify(radii, null, 2)} as const;\n\n` +
    `export const typography = ${JSON.stringify(typography, null, 2)} as const;\n\n` +
    `export const fonts = ${JSON.stringify(fonts, null, 2)} as const;\n`;

  fs.writeFileSync(path.join(REPO, 'src/brand/tokens.generated.ts'), brandTs);
  fs.writeFileSync(path.join(REPO, 'src/theme/tokens.generated.ts'), themeTs);

  const design = fonts.nativeDesign === 'rounded' ? '.rounded' : '.default';
  const brandColorConsts = Object.entries(brandColors)
    .filter(([, v]) => typeof v === 'string' && v.startsWith('#'))
    .map(([k, v]) => `  static let ${k} = Color(hex: ${hex(v)})`)
    .join('\n');

  const brandGrad = gradients.brand;
  const darkBg = gradients.darkBackground;
  const lightBg = gradients.lightBackground;
  const fallbackGrad =
    'LinearGradient(colors: [.clear], startPoint: .top, endPoint: .bottom)';

  const swift =
    header(
      'BrandTokens — colors/gradients for Widget + Watch (add to Xcode target when wiring).',
    ) +
    `
import SwiftUI

extension Color {
  init(hex: UInt32) {
    self.init(
      .sRGB,
      red: Double((hex >> 16) & 0xFF) / 255,
      green: Double((hex >> 8) & 0xFF) / 255,
      blue: Double(hex & 0xFF) / 255,
      opacity: 1
    )
  }
}

enum BrandTokens {
  // Brand identity — used by the shared Symply Widget/Watch kit to read this brand's
  // App Group data and pick per-app content. Regenerated per APP_BRAND at build.
  static let brandId = "${brandId}"
  static let appKey = "${appKey}"
  static let appGroup = "${appGroup}"

${brandColorConsts}

  static var mint: Color { primary }
  static var mintDark: Color { primaryDark }

  static let brandGradient = ${brandGrad ? swiftGradient(brandGrad) : fallbackGrad}

  static func background(_ scheme: ColorScheme) -> LinearGradient {
    scheme == .dark
      ? ${darkBg ? swiftGradient(darkBg) : fallbackGrad}
      : ${lightBg ? swiftGradient(lightBg) : fallbackGrad}
  }

  static func primaryText(_ scheme: ColorScheme) -> Color {
    scheme == .dark ? ${colorSwift(modes.dark?.text ?? '#FFFFFF')} : ${colorSwift(modes.light?.text ?? '#000000')}
  }

  static let fontDesign: Font.Design = ${design}
  static func font(_ size: CGFloat, _ weight: Font.Weight = .regular) -> Font {
    .system(size: size, weight: weight, design: fontDesign)
  }
}
`;

  fs.writeFileSync(
    path.join(REPO, 'ios/SymplyEcosystemWidget/DesignTokens.generated.swift'),
    swift,
  );

  console.log(`✓ Rebuilt design tokens for brand "${brandId}"`);
  console.log('  → src/brand/tokens.generated.ts');
  console.log('  → src/theme/tokens.generated.ts');
  console.log('  → ios/SymplyEcosystemWidget/DesignTokens.generated.swift');
}

main();
