// GENERATED by scripts/build-tokens.mjs (APP_BRAND=symply-budget) — DO NOT EDIT.
// Sources: brands/_shared/tokens.base.json + brands/symply-budget/tokens.json
// Run: APP_BRAND=symply-budget npm run design:build
// Brand colors, gradients, modes, semantic for the RN app.

export const brandColors = {
  "primary": "#2BB673",
  "primaryDark": "#239A61",
  "primaryLight": "#5FD49A",
  "primaryOnDark": "#239A61",
  "primaryDarkOnDark": "#1B7A4C",
  "white": "#FFFFFF",
  "ink": "#0A1325"
} as const;

export const gradients = {
  "brand": {
    "colors": [
      "#2BB673",
      "#239A61",
      "#1B7A4C"
    ],
    "locations": [
      0,
      0.5,
      1
    ],
    "start": {
      "x": 0,
      "y": 0
    },
    "end": {
      "x": 1,
      "y": 1
    }
  },
  "cta": {
    "colors": [
      "#2BB673",
      "#1A6B8A"
    ],
    "locations": [
      0,
      1
    ],
    "start": {
      "x": 0,
      "y": 0
    },
    "end": {
      "x": 1,
      "y": 0
    }
  },
  "secondary": {
    "colors": [
      "#4C8DFF",
      "#5C79F2",
      "#6B5CE0"
    ],
    "locations": [
      0,
      0.5,
      1
    ],
    "start": {
      "x": 0,
      "y": 0
    },
    "end": {
      "x": 1,
      "y": 0
    }
  },
  "darkBackground": {
    "colors": [
      "#0A1325",
      "#122033",
      "#1A2A3A"
    ],
    "locations": [
      0,
      0.55,
      1
    ],
    "start": {
      "x": 0.05,
      "y": 0
    },
    "end": {
      "x": 0.95,
      "y": 1
    }
  },
  "lightBackground": {
    "colors": [
      "#FFFFFF",
      "#EAF8F1",
      "#D9F2E6"
    ],
    "locations": [
      0,
      0.4,
      1
    ],
    "start": {
      "x": 0.5,
      "y": 0
    },
    "end": {
      "x": 0.5,
      "y": 1
    }
  }
} as const;

export const themeColors = {
  "dark": {
    "background": "#0A1325",
    "text": "#F7FAFF",
    "secondaryText": "#9EADC2",
    "hairline": "rgba(255,255,255,0.10)"
  },
  "light": {
    "background": "#FAFCFF",
    "text": "#0A1325",
    "secondaryText": "#627089",
    "hairline": "rgba(10,25,48,0.09)"
  }
} as const;

export const semantic = {
  "error": "#FF3B30",
  "success": "#34C759",
  "warning": "#FF9F0A",
  "info": "#4ECDC4"
} as const;
